"""Initial schema.

Every table, index, constraint and column comment the models declare, plus
the three trigger functions and the fifteen triggers that are not in the
models and so are written out by hand below.

The `vector` and `pg_trgm` extensions are created first, so that an
`alembic upgrade head` against a bare database builds a working schema on its
own. The downgrade leaves them in place.

Revision: fcaaa00f8b88
Parent:   -
Created:  2026-09-27
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "fcaaa00f8b88"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: A deletion is kept as jsonb rather than lost, and a link table deleting its
#: last row takes the parent with it. Neither is in the models, so neither is
#: autogenerated: they are written here and asserted by the schema tests.
_FUNCTIONS = (
    """
CREATE OR REPLACE FUNCTION archive_deleted_row() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO archived_rows (table_name, payload)
    VALUES (TG_TABLE_NAME, to_jsonb(OLD) - 'embedding');
    RETURN NULL;
END;
$$;
""",
    """
CREATE OR REPLACE FUNCTION delete_fact_without_passage() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM facts WHERE id = OLD.fact_id;
    RETURN NULL;
END;
$$;
""",
    """
CREATE OR REPLACE FUNCTION delete_question_without_facts() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM questions q
     WHERE q.id = OLD.question_id
       AND NOT EXISTS (
           SELECT 1 FROM question_facts qf WHERE qf.question_id = q.id
       );
    RETURN NULL;
END;
$$;
""",
)

#: Every table whose deletions are archived. `archived_rows` is not one: it is
#: where they land.
_ARCHIVED = (
    "documents",
    "passages",
    "facts",
    "fact_passages",
    "questions",
    "question_facts",
    "topics",
    "passage_topics",
    "ingest_events",
    "service_settings",
    "prompts",
    "assessments",
    "assessment_metrics",
)


def upgrade() -> None:
    """Applies the change."""
    # Before the tables: a vector column needs the type to exist. configs/
    # postgres/init.sh creates these too, but only under compose and only on
    # an empty volume - every other database is built by this revision alone.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archived_rows",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "table_name",
            sa.Text(),
            nullable=False,
            comment="The table the row was deleted from.",
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="The whole row, by column name, minus `embedding`. A vector renders as about 13 kB of text per row - ten times everything else the row holds - and is recomputed from the text it belongs to, so keeping it would cost ten archives and buy one. Every other column is here, the primary key included, so jsonb_populate_record puts a row back by hand.",
        ),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the deletion happened.",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Every row deleted from every other table, as it was. Filled by an AFTER DELETE trigger rather than by the application, so a foreign key cascade, an orphan trigger and a statement typed into psql are archived alike. Nothing archives this table: emptying it is the second deletion.",
    )
    op.create_index(
        "ix_archived_rows_archived_at", "archived_rows", ["archived_at"], unique=False
    )
    op.create_index(
        "ix_archived_rows_table_name", "archived_rows", ["table_name"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column(
            "sha256",
            sa.CHAR(length=64),
            nullable=False,
            comment="SHA-256 of the raw file bytes, and the object key in both buckets: documents/{sha[0:2]}/{sha[2:4]}/{sha}.{ext} and parsed/.../{sha}.json. Both keys are derived in code, never stored.",
        ),
        sa.Column(
            "mime_type",
            sa.Text(),
            nullable=False,
            comment="Detected from the leading bytes at upload.",
        ),
        sa.Column(
            "page_count",
            sa.Integer(),
            nullable=True,
            comment="Pages, counted by PyMuPDF at upload.",
        ),
        sa.Column(
            "char_count",
            sa.Integer(),
            nullable=True,
            comment="Extractable characters, counted by PyMuPDF at upload.",
        ),
        sa.Column(
            "language",
            sa.CHAR(length=2),
            nullable=True,
            comment="ISO 639-1, NULL until parsing detects it. The fallback pipeline for a passage of this document too short to tell its own language; `passages.language` is what selects one where it has it.",
        ),
        sa.Column(
            "title",
            sa.Text(),
            nullable=True,
            comment="Document title, written by parsing.",
        ),
        sa.Column(
            "content_sha256",
            sa.CHAR(length=64),
            nullable=True,
            comment='SHA-256 of the body text with whitespace collapsed and case folded. Answers "do we already have this content?" on request; nothing acts on it at ingest.',
        ),
        sa.Column(
            "parse_confidence",
            sa.Float(),
            nullable=True,
            comment="Mean confidence the parser reported, in [0, 1].",
        ),
        sa.Column(
            "parse_confidence_low",
            sa.Float(),
            nullable=True,
            comment="Confidence of the worst page, which is the one worth reviewing.",
        ),
        sa.Column(
            "parse_status",
            sa.Text(),
            server_default="new",
            nullable=False,
            comment="new | pending | in_progress | parsed | failed.",
        ),
        sa.Column(
            "parse_error",
            sa.Text(),
            nullable=True,
            comment="Why a failed document failed to parse.",
        ),
        sa.Column(
            "parse_claimed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When a worker claimed this document for parsing, NULL when none holds it. What tells a live claim from one a dead worker left behind.",
        ),
        sa.Column(
            "parse_run_id",
            sa.Text(),
            nullable=True,
            comment="Which run parsed this document, as `settings.runs.run_id` named it. NULL for a document parsed before the run was recorded.",
        ),
        sa.Column(
            "parse_trigger",
            sa.Text(),
            nullable=True,
            comment="Which run asked for this document to be parsed, written by whatever queued it and adopted by the worker that claims it. NULL where nobody named a run, and the worker's own id is used instead.",
        ),
        sa.Column(
            "parse_trace_id",
            sa.Text(),
            nullable=True,
            comment="The OpenTelemetry trace this document was parsed in, as 32 hex characters. <phoenix>/redirects/traces/<trace_id> opens it.",
        ),
        sa.Column(
            "parse_span_id",
            sa.Text(),
            nullable=True,
            comment="The span the parse ran in, as 16 hex characters. <phoenix>/redirects/spans/<span_id> opens it.",
        ),
        sa.Column(
            "chunk_status",
            sa.Text(),
            server_default="new",
            nullable=False,
            comment="new | pending | in_progress | chunked | failed. The only column chunking reads to find work: it does not consult parse_status, because a stage knows of no other stage.",
        ),
        sa.Column(
            "chunk_error",
            sa.Text(),
            nullable=True,
            comment="Why a failed document failed to chunk.",
        ),
        sa.Column(
            "chunk_claimed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When a worker claimed this document for chunking, NULL when none holds it.",
        ),
        sa.Column(
            "chunk_trigger",
            sa.Text(),
            nullable=True,
            comment="Which run asked for this document to be chunked. See `parse_trigger`.",
        ),
        sa.Column(
            "oversized",
            sa.Integer(),
            nullable=True,
            comment="Passages the last chunking run stored above EMBEDDING_MAX_TOKENS. Expected to be 0: the chunker splits on that budget, so anything above it means the split did not happen. A tripwire; chunking discards nothing.",
        ),
        sa.CheckConstraint(
            "chunk_status IN ('new', 'pending', 'in_progress', 'failed', 'chunked')",
            name="documents_chunk_status_valid",
        ),
        sa.CheckConstraint(
            "language ~ '^[a-z]{2}$'", name="documents_language_is_iso_639_1"
        ),
        sa.CheckConstraint(
            "parse_status IN ('new', 'pending', 'in_progress', 'failed', 'parsed')",
            name="documents_parse_status_valid",
        ),
        sa.CheckConstraint(
            "parse_confidence BETWEEN 0 AND 1 AND parse_confidence_low BETWEEN 0 AND 1",
            name="documents_parse_confidence_is_a_probability",
        ),
        sa.PrimaryKeyConstraint("sha256"),
        comment="One stored source document. Everything about the act of uploading it lives in ingest_events.",
    )
    op.create_index(
        "ix_documents_chunk_queue",
        "documents",
        ["sha256"],
        unique=False,
        postgresql_where=sa.text("chunk_status IN ('pending', 'in_progress')"),
    )
    op.create_index(
        "ix_documents_parse_queue",
        "documents",
        ["sha256"],
        unique=False,
        postgresql_where=sa.text("parse_status IN ('pending', 'in_progress')"),
    )
    op.create_index(
        op.f("ix_documents_parse_run_id"), "documents", ["parse_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_documents_parse_span_id"), "documents", ["parse_span_id"], unique=False
    )
    op.create_index(
        op.f("ix_documents_parse_trace_id"),
        "documents",
        ["parse_trace_id"],
        unique=False,
    )
    op.create_table(
        "facts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "kind",
            sa.Text(),
            server_default="atomic",
            nullable=False,
            comment="atomic | summary | outline | bridge. Decides which checks the statement is held to and how many passages it rests on: atomic, summary and outline rest on one, a bridge on two or more.",
        ),
        sa.Column(
            "statement",
            sa.Text(),
            nullable=False,
            comment="The fact as written. One self-contained sentence for an atomic fact or a bridge, a short paragraph for a summary, and newline-separated `- ` bullets for an outline.",
        ),
        sa.Column(
            "evidence_text",
            sa.Text(),
            nullable=False,
            comment="Every span in fact_passages, resolved and joined in position order. The denormalised copy the search index reads; the spans themselves are the record.",
        ),
        sa.Column(
            "extraction_method",
            sa.Text(),
            nullable=False,
            comment="llm | deterministic.",
        ),
        sa.Column(
            "extraction_model",
            sa.Text(),
            nullable=True,
            comment="The model that wrote the statement, NULL if none did.",
        ),
        sa.Column(
            "prompt_version",
            sa.Text(),
            nullable=True,
            comment="Version of the extraction prompt. The prompt decides what counts as a fact, so two prompts are two datasets.",
        ),
        sa.Column(
            "extraction_temperature",
            sa.Float(),
            nullable=True,
            comment="Sampling temperature used.",
        ),
        sa.Column(
            "spacy_model",
            sa.Text(),
            nullable=True,
            comment="The spaCy pipeline that judged this fact.",
        ),
        sa.Column(
            "spacy_version",
            sa.Text(),
            nullable=True,
            comment="spaCy version. The parser decides the verdict, so it is provenance in the same way the prompt version is.",
        ),
        sa.Column(
            "settings_version",
            sa.Text(),
            nullable=True,
            comment="The configuration this fact was extracted under, as the digest settings.store computes, or 'environment' when nothing was overridden. The columns above name the model and the prompt; this names the rest of it, including the shares the checks held this fact to. NULL for a fact written before a setting could be changed without a restart.",
        ),
        sa.Column(
            "run_id",
            sa.Text(),
            nullable=True,
            comment="Which RUN produced this row, as `settings.runs.run_id` named it: RUN_ID where a caller set one, and a uuid otherwise. settings_version beside it names the CONFIGURATION, and two runs under one configuration carry the same version - so comparing a change against the run before it needs this column and cannot be done with that one. NULL for a row written before runs were named.",
        ),
        sa.Column(
            "trace_id",
            sa.Text(),
            nullable=True,
            comment="The OpenTelemetry trace this fact was extracted and checked in, as 32 hex characters.",
        ),
        sa.Column(
            "span_id",
            sa.Text(),
            nullable=True,
            comment="The span the extraction ran in, as 16 hex characters. One span per passage, so every fact from one passage shares it.",
        ),
        sa.Column(
            "statement_predicates",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Finite verbs in the statement. One is atomic; more means several claims in one sentence, none means no claim at all.",
        ),
        sa.Column(
            "evidence_predicates",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Finite verbs in the cited sentences. Against statement_predicates, how far the passage was decomposed.",
        ),
        sa.Column(
            "units_statement",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            comment="The numbers, proper nouns and predicates the statement asserts, which are the parts of it a paraphrase cannot change.",
        ),
        sa.Column(
            "units_added",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            comment="Units of the statement that occur nowhere in the cited sentences, in any form. Empty on every accepted fact, which is what says nothing was invented.",
        ),
        sa.Column(
            "unresolved_references",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            comment="Pronouns leaving the statement dependent on its context. Empty on every accepted atomic fact and bridge, which is what makes a question from one answerable alone. A summary and an outline are not held to it: they stand in for a whole passage rather than assert something about it, so they are checked on length and on inventing nothing and may open with a pronoun.",
        ),
        sa.Column(
            "validated",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Whether every check passed.",
        ),
        sa.Column(
            "rejection_code",
            sa.Text(),
            nullable=True,
            comment="Which check failed, NULL when none did.",
        ),
        sa.Column(
            "validation_error",
            sa.Text(),
            nullable=True,
            comment="That failure in words.",
        ),
        sa.Column(
            "gate_scores",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="One entry per measuring check that read this fact: the check, the value it measured, the threshold it was read against and the margin between them. A check that is structural rather than a measurement records nothing here - a citation resolves or it does not. NULL for a fact written before this column.",
        ),
        sa.Column(
            "confidence",
            sa.Float(),
            nullable=True,
            comment="The smallest margin in gate_scores, in [0, 1]. How close this fact came to the verdict that would have refused it, NOT a probability. NULL when no measuring check read it, which is most facts: nearly every check here is structural.",
        ),
        sa.Column(
            "reviewed_verdict",
            sa.Text(),
            nullable=True,
            comment="What a person decided about this fact: accepted or rejected. NULL means nobody has looked, which is most facts - a review is a sample. Separate from `validated`, which is the checker's and is rewritten in full by extract-revalidate.",
        ),
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the verdict above was recorded. NULL exactly when reviewed_verdict is.",
        ),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1024),
            nullable=True,
            comment="Statement embedding, used by the dedup gate. That gate cosine-searches every validated fact, which the HNSW index above serves. The same width and the same model as questions.embedding and passages.embedding: one corpus is measured in one space, so a fact and the question resting on it are comparable. NULL on a fact extracted before the column existed, and on one no deployment asked to embed - EXTRACTION_DUPLICATE_COSINE at 0 turns the gate and the embedding off together.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the fact was extracted.",
        ),
        sa.CheckConstraint(
            "extraction_method <> 'llm' OR validated IS FALSE OR cardinality(units_added) = 0",
            name="facts_accepted_invented_nothing",
        ),
        sa.CheckConstraint(
            "extraction_method <> 'llm' OR validated IS FALSE OR kind NOT IN ('atomic', 'bridge') OR cardinality(unresolved_references) = 0",
            name="facts_accepted_claim_stands_alone",
        ),
        sa.CheckConstraint(
            "extraction_method IN ('llm', 'deterministic')",
            name="facts_extraction_method_valid",
        ),
        sa.CheckConstraint(
            "kind IN ('atomic', 'summary', 'outline', 'bridge')",
            name="facts_kind_valid",
        ),
        sa.CheckConstraint(
            "rejection_code IS NULL OR rejection_code IN ('evidence_absent', 'copied', 'asserts_nothing', 'not_atomic', 'unsupported_addition', 'unresolved_reference', 'not_condensed', 'not_listed', 'not_bridging', 'over_cap', 'duplicate')",
            name="facts_rejection_code_valid",
        ),
        sa.CheckConstraint(
            "reviewed_verdict IS NULL OR reviewed_verdict IN ('accepted', 'rejected')",
            name="facts_reviewed_verdict_valid",
        ),
        sa.CheckConstraint(
            "(reviewed_verdict IS NULL) = (reviewed_at IS NULL)",
            name="facts_reviewed_together",
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name="facts_confidence_is_a_share",
        ),
        sa.CheckConstraint(
            "validated = (rejection_code IS NULL)", name="facts_verdict_agrees"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="One statement and the verdicts the checks reached on it. Which passages it rests on, and where in each, is fact_passages. The unit a question is generated from and scored against.",
    )
    op.create_index(
        "ix_facts_confidence",
        "facts",
        ["confidence"],
        unique=False,
        postgresql_where=sa.text("confidence IS NOT NULL"),
    )
    op.create_index(
        "ix_facts_embedding_hnsw",
        "facts",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_facts_evidence_trgm",
        "facts",
        ["evidence_text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"evidence_text": "gin_trgm_ops"},
    )
    op.create_index("ix_facts_kind", "facts", ["kind"], unique=False)
    op.create_index(
        "ix_facts_rejection_code", "facts", ["rejection_code"], unique=False
    )
    op.create_index(
        "ix_facts_reviewed_verdict",
        "facts",
        ["reviewed_verdict"],
        unique=False,
        postgresql_where=sa.text("reviewed_verdict IS NOT NULL"),
    )
    op.create_index(op.f("ix_facts_run_id"), "facts", ["run_id"], unique=False)
    # Partial: the column is low-cardinality and mostly NULL. The model
    # declares the predicate too, but autogenerate does not compare one, so
    # this stays written out rather than left to a later regeneration.
    op.create_index(
        op.f("ix_facts_settings_version"),
        "facts",
        ["settings_version"],
        unique=False,
        postgresql_where=sa.text("settings_version IS NOT NULL"),
    )
    op.create_index(op.f("ix_facts_span_id"), "facts", ["span_id"], unique=False)
    op.create_index(
        "ix_facts_statement_trgm",
        "facts",
        ["statement"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"statement": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_facts_trace_id"), "facts", ["trace_id"], unique=False)
    op.create_table(
        "prompts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "service",
            sa.Text(),
            nullable=False,
            comment="Which stage sends it: extraction or questions. The stage writes its own and no other's, because no backend service imports another.",
        ),
        sa.Column(
            "name",
            sa.Text(),
            nullable=False,
            comment="What the prompt is, within its service: a question type, `perturb`, `follow`, one of the phrasing judgements, or one of the verifier's four.",
        ),
        sa.Column(
            "version",
            sa.Text(),
            nullable=False,
            comment="The PROMPT_VERSION its module declared when this text was written. Indexed: resolving a question's prompt_version is the query this table is for.",
        ),
        sa.Column(
            "text",
            sa.Text(),
            nullable=False,
            comment="The SYSTEM prompt as composed, which is what the model was given as its instructions.",
        ),
        sa.Column(
            "user_text",
            sa.Text(),
            server_default="",
            nullable=False,
            comment="The USER message as its template, with `{{name}}` where the call fills a passage, a fact or a question in. Every call sends both halves; this is the one the row used not to carry, so Phoenix showed a system message and nothing under it. Empty on a row recorded before the column existed.",
        ),
        sa.Column(
            "response_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="The JSON schema the answer had to come back in, from the Pydantic shape the call asks for. NULL on a row recorded before the column existed, which is not the same as a call that asked for no shape - there is no such call.",
        ),
        sa.Column(
            "model",
            sa.Text(),
            nullable=True,
            comment="Which model this prompt is sent to, where the stage names one instead of the shared LLM_MODEL. A name and not a setting: the publisher resolves the rest through llm.config.Settings.overridden. NULL means the stage's own model, which is what a row recorded before this column existed means too.",
        ),
        sa.Column(
            "digest",
            sa.Text(),
            nullable=False,
            comment="The first sixteen hex characters of the text's SHA-256, spelled as tests/static/test_prompts_pinned.py spells it, so a row and that file's pin can be compared by eye. What a changed prompt under an unchanged version is noticed by at run time.",
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this version of this prompt was first recorded. Not updated when the text is rewritten under the same version: what that would record is the last restart, and the warning is where a rewrite is reported.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the text was last written. Moves only when the text actually changed, which under an unchanged version is drift.",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "service", "version", "name", name="prompts_service_version_name_unique"
        ),
        comment="Every prompt this pipeline sends, as it was composed, keyed by the PROMPT_VERSION that composed it. What facts.prompt_version and questions.prompt_version point at. Written at stage start-up from the source; read-only to everything else, and editing a row changes nothing about what is sent.",
    )
    op.create_index(op.f("ix_prompts_service"), "prompts", ["service"], unique=False)
    op.create_index(op.f("ix_prompts_version"), "prompts", ["version"], unique=False)
    op.create_table(
        "questions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "question_text",
            sa.Text(),
            nullable=False,
            comment="The question as it would be put to the chatbot.",
        ),
        sa.Column(
            "target_answer",
            sa.Text(),
            nullable=True,
            comment="The expected answer. Must be NULL when answerable is false, enforced by a CHECK constraint: an unanswerable question is scored on behaviour, not on content.",
        ),
        sa.Column(
            "answer_explanation",
            sa.Text(),
            nullable=True,
            comment="The same answer said at length, for a reader who has not seen the material. Separate from target_answer because the two are scored differently: recoverability compares the target whole, and every lemma added to it is another one the verifier has to reproduce, so an answer that teaches cannot also be the answer that is matched. NULL on every question written before this column, and on every unanswerable one.",
        ),
        sa.Column(
            "answerable",
            sa.Boolean(),
            nullable=False,
            comment="Whether the document supports an answer at all. False for the deliberately unanswerable questions that test whether the chatbot recognises the limits of its knowledge.",
        ),
        sa.Column(
            "difficulty",
            sa.Text(),
            nullable=True,
            comment="easy | medium | hard, enforced by a CHECK constraint. Derived rather than judged: the three scope columns, a long answer and being a follow-up are each worth a point, and the band is the total. Two readers cannot disagree about it, and a review sample can stratify on it.",
        ),
        sa.Column(
            "question_type",
            sa.Text(),
            nullable=True,
            comment="What the question asks for, enforced by a CHECK constraint: factoid, definition, entity, enumeration, condition, reason, procedure, consequence, comparison, aggregation or temporal. Requested by the plan before the question is written, not read off it afterwards. QUESTIONS_TYPE_MIX sets which are written and in what proportion.",
        ),
        sa.Column(
            "answer_form",
            sa.Text(),
            nullable=True,
            comment="value | list | explanation, enforced by a CHECK constraint. The shape the target answer takes, declared by the question type. The gates read it: a value carries no verb, an explanation does, and each form has its own length bounds in QUESTIONS_ANSWER_CHARS.",
        ),
        sa.Column(
            "planned_difficulty",
            sa.Text(),
            nullable=True,
            comment="The band QUESTIONS_DIFFICULTY_MIX asked for, enforced by a CHECK constraint. `difficulty` beside it is what the question turned out to be. The two disagree when the writer cited fewer facts than it was offered, which is a measurement of the plan rather than a fault in the row.",
        ),
        sa.Column(
            "passage_scope",
            sa.Text(),
            nullable=True,
            comment="single_passage | multi_passage, enforced by a CHECK constraint. How many distinct passages the facts this question cites come from.",
        ),
        sa.Column(
            "document_scope",
            sa.Text(),
            nullable=True,
            comment="single_document | cross_document, enforced by a CHECK constraint. The scope a retriever cannot fake: a cross-document question has no one chunk holding its answer.",
        ),
        sa.Column(
            "topic_scope",
            sa.Text(),
            nullable=True,
            comment="single_topic | multi_topic, enforced by a CHECK constraint. Read off the dominant topic of each cited fact's passage. A passage usually sits in several topics above the weight floor, so a question bridging two subjects is one about the material rather than about a section of it.",
        ),
        sa.Column(
            "answer_chars",
            sa.Integer(),
            nullable=True,
            comment="Length of target_answer, stored rather than measured on read so the difficulty band it fed can be recomputed and checked. NULL on an unanswerable question, which has no answer to measure.",
        ),
        sa.Column(
            "follows_id",
            sa.BigInteger(),
            nullable=True,
            comment="The question this one follows, for a multi-turn thread. NULL on a root question. A follow-up may rely on its parent for context - that is what it is for - so it is deliberately not self-contained and the phrasing gate is not applied to one. Cascades: a follow-up whose parent is gone has no thread to be read in.",
        ),
        sa.Column(
            "thread_position",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
            comment="Where this question sits in its thread: 1 is a root, 2 is the first follow-up. QUESTIONS_MAX_FOLLOWUPS caps how far it goes.",
        ),
        sa.Column(
            "language",
            sa.CHAR(length=2),
            nullable=False,
            comment="ISO 639-1 language the question is written in, constrained to the shape of a code rather than to a list of them. Deliberately independent of the source document's language: a German document can carry English questions.",
        ),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1024),
            nullable=True,
            comment="Question embedding, used by the semantic dedup and unanswerability gates. Those do cosine search over every accepted question, which the HNSW index above serves. 1024 dimensions because that is the width of EMBEDDING_MODEL, which is also the tokenizer chunking sizes a passage by - one name in .env for both, so a passage cannot be sized against one model and embedded by another. Changing that model means a migration here and re-embedding every row; pgvector indexes HNSW up to 2000 dimensions, so a wider model than that must be truncated, which Matryoshka training supports.",
        ),
        sa.Column(
            "status",
            sa.Text(),
            server_default="draft",
            nullable=False,
            comment="draft | accepted | rejected, enforced by a CHECK constraint. Rejected questions are never deleted: they are the drop-rate evidence in the coverage report.",
        ),
        sa.Column(
            "rejected_reason",
            sa.Text(),
            nullable=True,
            comment="Which gate rejected the question, enforced by a CHECK constraint. NULL on a question a person rejected from the page, which names no gate.",
        ),
        sa.Column(
            "gates_ran",
            postgresql.ARRAY(sa.Text()),
            nullable=True,
            comment="Every gate that read this question, in the order they read it, the one that refused it last. question_generation.checker.GATES gives each its fixed position. Two gates are conditional, so this cannot be derived from rejected_reason and a fixed order. NULL for a question written before this column; empty means no gate ran.",
        ),
        sa.Column(
            "gates_abstained",
            postgresql.ARRAY(sa.Text()),
            nullable=True,
            comment="Every judgement this question was meant to get and could not, because the model could not be reached. A gate that abstained is NOT a gate that passed: the checker rejects on False and an abstention is None, so without this the question reads as having cleared a gate nobody ran. NULL for a question written before this column; empty means every gate that was asked answered.",
        ),
        sa.Column(
            "attempt",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
            comment="Which attempt at this question's slot wrote it: 1 is the first draft and anything above it is a retry QUESTIONS_RETRIES paid for. Every draft is stored, refused ones included, so this is what makes the yield of a retry a query rather than a guess.",
        ),
        sa.Column(
            "gate_scores",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="One entry per measuring gate that read this question: the gate, the value it measured, the threshold it was read against and the margin between them. A gate that is a judgement rather than a measurement records nothing here, because an opinion has no number behind it. NULL for a question written before this column.",
        ),
        sa.Column(
            "confidence",
            sa.Float(),
            nullable=True,
            comment="The smallest margin in gate_scores, in [0, 1]. How close this question came to the verdict that would have refused it, NOT a probability: the readings are on different scales and only the margins are comparable. NULL when no measuring gate read it, which is different from 0.",
        ),
        sa.Column(
            "reviewed_verdict",
            sa.Text(),
            nullable=True,
            comment="What a person decided about this question: accepted or rejected. NULL means nobody has looked, which is most questions - a review is a sample. Separate from `status`, which is what the question IS, and from `rejected_reason`, which is the gate's; holding all three is what makes the agreement between a reviewer and the checker a query.",
        ),
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the verdict above was recorded. NULL exactly when reviewed_verdict is.",
        ),
        sa.Column(
            "cognitive_level",
            sa.Text(),
            nullable=True,
            comment="recall | understand | apply | analyse, enforced by a CHECK constraint. How much the question asks of whoever answers it, declared by its type rather than judged per row - the same bargain difficulty makes with the scopes. A different axis from difficulty, and deliberately not merged with it: difficulty says how far the answer is spread and so how hard it is to FIND, and a question spanning two documents can still be a bare lookup once both are in hand. This says how much has to be done with what was found.",
        ),
        sa.Column(
            "release_id",
            sa.Uuid(),
            nullable=True,
            comment="The balanced release this question was chosen into; one UUID per draw. Accepting a question says it is sound, which is a different question from what the SET should look like: `make questions-balance` fills an even quota of kinds and difficulty bands out of everything accepted, and writes this. NULL means accepted but not drawn - kept, queryable, and available to the next draw.",
        ),
        sa.Column(
            "settings_version",
            sa.Text(),
            nullable=True,
            comment="The configuration this question was written under, as the digest settings.store computes, or 'environment' when nothing was overridden. Which model wrote it, what mix the plan aimed for and what bounds the gates held it to are all in the settings that version names. NULL for a question written before a setting could be changed without a restart.",
        ),
        sa.Column(
            "trace_id",
            sa.Text(),
            nullable=True,
            comment="The OpenTelemetry trace this question was written and judged in, as 32 hex characters. What gets from a row to the calls that produced it: Phoenix resolves a trace from this alone, so <phoenix>/redirects/traces/<trace_id> opens it without anything knowing Phoenix's internal ids. NULL for a question written before this column, and for one written by a process exporting no spans.",
        ),
        sa.Column(
            "span_id",
            sa.Text(),
            nullable=True,
            comment="The span the gates ran in, as 16 hex characters, which is the span this question's verdict annotations hang off. Stored beside the trace because it is the more useful of the two: /redirects/spans/ opens the gate decision itself rather than the whole topic. The span cannot carry the question id instead - the question has none yet when the gates run.",
        ),
        sa.Column(
            "prompt_version",
            sa.Text(),
            nullable=True,
            comment="Version of the prompt that wrote this question, as question_generation.types.PROMPT_VERSION declares it. The prompt decides what a question IS, so two prompts are two datasets - the same reason facts.prompt_version exists. Not covered by settings_version, which is a digest of the stored overrides and does not move when a prompt is edited. NULL for a question written before the version was recorded.",
        ),
        sa.Column(
            "run_id",
            sa.Text(),
            nullable=True,
            comment="Which RUN produced this row, as `settings.runs.run_id` named it: RUN_ID where a caller set one, and a uuid otherwise. settings_version beside it names the CONFIGURATION, and two runs under one configuration carry the same version - so comparing a change against the run before it needs this column and cannot be done with that one. NULL for a row written before runs were named.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the question was generated.",
        ),
        sa.Column(
            "status_changed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When status last changed.",
        ),
        sa.CheckConstraint(
            "answer_form IS NULL OR answer_form IN ('value', 'list', 'explanation')",
            name="questions_answer_form_valid",
        ),
        sa.CheckConstraint(
            "cognitive_level IS NULL OR cognitive_level IN ('recall', 'understand', 'apply', 'analyse')",
            name="questions_cognitive_level_valid",
        ),
        sa.CheckConstraint(
            "difficulty IS NULL OR difficulty IN ('easy', 'medium', 'hard')",
            name="questions_difficulty_valid",
        ),
        sa.CheckConstraint(
            "document_scope IS NULL OR document_scope IN ('single_document', 'cross_document')",
            name="questions_document_scope_valid",
        ),
        sa.CheckConstraint(
            "language ~ '^[a-z]{2}$'", name="questions_language_is_iso_639_1"
        ),
        sa.CheckConstraint(
            "passage_scope IS NULL OR passage_scope IN ('single_passage', 'multi_passage')",
            name="questions_passage_scope_valid",
        ),
        sa.CheckConstraint(
            "planned_difficulty IS NULL OR planned_difficulty IN ('easy', 'medium', 'hard')",
            name="questions_planned_difficulty_valid",
        ),
        sa.CheckConstraint(
            "question_type IS NULL OR question_type IN ('factoid', 'definition', 'entity', 'enumeration', 'condition', 'reason', 'procedure', 'consequence', 'comparison', 'aggregation', 'temporal', 'implication', 'application')",
            name="questions_question_type_valid",
        ),
        sa.CheckConstraint(
            "rejected_reason IS NULL OR rejected_reason IN ('malformed', 'compound', 'answer_too_short', 'answer_too_long', 'wrong_form', 'wrong_type', 'restates_question', 'explanation_unusable', 'answer_incomplete', 'leaks_source', 'unanchored', 'not_recoverable', 'duplicate', 'answerable_after_all', 'answerable_elsewhere', 'off_topic', 'asks_nothing_new', 'off_thread', 'source_changed')",
            name="questions_rejected_reason_valid",
        ),
        sa.CheckConstraint(
            "reviewed_verdict IS NULL OR reviewed_verdict IN ('accepted', 'rejected')",
            name="questions_reviewed_verdict_valid",
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'accepted', 'rejected')", name="questions_status_valid"
        ),
        sa.CheckConstraint(
            "topic_scope IS NULL OR topic_scope IN ('single_topic', 'multi_topic')",
            name="questions_topic_scope_valid",
        ),
        sa.CheckConstraint(
            "(follows_id IS NULL) = (thread_position = 1)",
            name="questions_thread_position_agrees",
        ),
        sa.CheckConstraint(
            "(reviewed_verdict IS NULL) = (reviewed_at IS NULL)",
            name="questions_reviewed_together",
        ),
        sa.CheckConstraint(
            "answerable OR answer_explanation IS NULL",
            name="questions_unanswerable_has_no_explanation",
        ),
        sa.CheckConstraint(
            "answerable OR target_answer IS NULL",
            name="questions_unanswerable_has_no_target",
        ),
        sa.CheckConstraint("attempt >= 1", name="questions_attempt_is_positive"),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name="questions_confidence_is_a_share",
        ),
        sa.CheckConstraint(
            "thread_position >= 1", name="questions_thread_position_valid"
        ),
        sa.ForeignKeyConstraint(["follows_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="The test questions themselves. Append-only and never hard-deleted: rejected questions are the drop-rate evidence in the coverage report. Deleting every fact a question came from also deletes the question: a foreign key cannot cascade that direction, so an AFTER DELETE trigger on question_facts does it.",
    )
    op.create_index(
        "ix_questions_confidence",
        "questions",
        ["confidence"],
        unique=False,
        postgresql_where=sa.text("confidence IS NOT NULL"),
    )
    op.create_index(
        "ix_questions_embedding_hnsw",
        "questions",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_questions_follows_id", "questions", ["follows_id"], unique=False
    )
    op.create_index(
        op.f("ix_questions_prompt_version"),
        "questions",
        ["prompt_version"],
        unique=False,
    )
    op.create_index(
        "ix_questions_question_type", "questions", ["question_type"], unique=False
    )
    op.create_index(
        op.f("ix_questions_release_id"), "questions", ["release_id"], unique=False
    )
    op.create_index(
        "ix_questions_reviewed_verdict",
        "questions",
        ["reviewed_verdict"],
        unique=False,
        postgresql_where=sa.text("reviewed_verdict IS NOT NULL"),
    )
    op.create_index(op.f("ix_questions_run_id"), "questions", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_questions_settings_version"),
        "questions",
        ["settings_version"],
        unique=False,
        postgresql_where=sa.text("settings_version IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_questions_span_id"), "questions", ["span_id"], unique=False
    )
    op.create_index("ix_questions_status", "questions", ["status"], unique=False)
    op.create_index(
        op.f("ix_questions_trace_id"), "questions", ["trace_id"], unique=False
    )
    op.create_table(
        "service_settings",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "service",
            sa.Text(),
            nullable=False,
            comment="Which service configures it: ingestion, parsing, chunking, extraction, topics, questions or platform. Denormalised from settings.catalog so one service's settings are one query.",
        ),
        sa.Column(
            "name",
            sa.Text(),
            nullable=False,
            comment="The variable, spelled as the environment spells it. Unique: two rows for one setting would make which value wins depend on row order.",
        ),
        sa.Column(
            "value",
            sa.Text(),
            nullable=False,
            comment="The value, as text, exactly as the environment would hand it over. Empty only for a setting whose absence means something, which is how one is overridden to absent; the store refuses an empty value for any other.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this setting was last written.",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="service_settings_name_unique"),
        comment="Settings changed through the API, the CLI or a page, one row per setting. An override over what configs/env/backend.env and .env say, never a default: deleting a row returns the setting to the file. Workers read this when they claim a row, so a change reaches them without a restart.",
    )
    op.create_index(
        op.f("ix_service_settings_service"),
        "service_settings",
        ["service"],
        unique=False,
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "language",
            sa.CHAR(length=2),
            nullable=True,
            comment="Which language's model this topic belongs to. Each language is fitted separately over its own vocabulary, because one model across both spends topics on telling the languages apart rather than on telling subjects apart. NULL on a fit request.",
        ),
        sa.Column(
            "topic_index",
            sa.Integer(),
            nullable=True,
            comment="Position of this topic in its language's fitted model, and the key scoring a passage returns. Unique per language, not overall. NULL means this row is a fit request rather than a topic.",
        ),
        sa.Column(
            "top_terms",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            comment="Highest-weighted terms, descending. The topic's readable identity and the only signature a label is matched on across a refit.",
        ),
        sa.Column(
            "label",
            sa.Text(),
            nullable=True,
            comment="The subject this topic is, in words.",
        ),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1024),
            nullable=True,
            comment="Where this topic sits, as the membership-weighted mean of its passages' vectors, normalised back to length 1. Derived rather than asked for: it is an average of passages.embedding computed in SQL, so no worker loads a model to write it and it cannot disagree with the passages it is the mean of. What it is for is telling two topics apart - a factorisation splits one subject in two often enough that the coverage report needs to say so. NULL until the passages are embedded.",
        ),
        sa.Column(
            "labelled_by",
            sa.Text(),
            nullable=True,
            comment="What named it: 'person', or the model identifier. A name a person typed is never overwritten by a model's, and a report that reads by name should say which it is reading.",
        ),
        sa.Column(
            "include_in_coverage",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Whether this topic counts toward coverage reporting. Carried across a refit with the label.",
        ),
        sa.Column(
            "status",
            sa.Text(),
            server_default="pending",
            nullable=False,
            comment="pending | in_progress | modelled | failed. A finished topic is modelled; the other three describe a fit.",
        ),
        sa.Column(
            "error",
            sa.Text(),
            nullable=True,
            comment="Why a fit failed, on the request row, which is kept beside the topics the previous fit produced.",
        ),
        sa.Column(
            "claimed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When a worker claimed this fit, NULL when none holds it.",
        ),
        sa.Column(
            "trigger",
            sa.Text(),
            nullable=True,
            comment="Which run asked for this fit. See `documents.parse_trigger`.",
        ),
        sa.Column(
            "question_status",
            sa.Text(),
            server_default="new",
            nullable=False,
            comment="new | pending | in_progress | failed | generated, enforced by a CHECK constraint. Question generation's own queue, over topics rather than over fits: the unit of work is one topic's facts. Meaningless on a fit request, which is why that queue carries topic_index IS NOT NULL. A fit replaces every row here, so a refit returns every topic to `new`; the questions themselves are not a topic's and survive it.",
        ),
        sa.Column(
            "question_error",
            sa.Text(),
            nullable=True,
            comment="Why question generation failed on this topic.",
        ),
        sa.Column(
            "question_claimed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When a worker claimed this topic for question generation, NULL when none holds it.",
        ),
        sa.Column(
            "question_trigger",
            sa.Text(),
            nullable=True,
            comment="Which run asked for questions on this topic. See `documents.parse_trigger`.",
        ),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the fit that produced this topic was asked for.",
        ),
        sa.Column(
            "fitted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the fit completed.",
        ),
        sa.Column(
            "corpus_passages",
            sa.Integer(),
            nullable=True,
            comment="How many passages of this language the model was fitted over. Compared against the live count to tell whether the topics still describe the corpus.",
        ),
        sa.Column(
            "corpus_vocabulary",
            sa.Integer(),
            nullable=True,
            comment="How many terms survived the frequency filter.",
        ),
        sa.Column(
            "passages_without_topics",
            sa.Integer(),
            nullable=True,
            comment="How many passages the fit could place in no topic. Those, and the facts drawn from them, are absent from every topic-weighted report.",
        ),
        sa.Column(
            "settings_version",
            sa.Text(),
            nullable=True,
            comment="The configuration this topic was fitted under, as the digest settings.store computes, or 'environment' when nothing was overridden. A fit is not reproducible without the parameters it used, and the seed is only one of them. NULL for a topic fitted before a setting could be changed without a restart.",
        ),
        sa.Column(
            "run_id",
            sa.Text(),
            nullable=True,
            comment="Which RUN produced this row, as `settings.runs.run_id` named it: RUN_ID where a caller set one, and a uuid otherwise. settings_version beside it names the CONFIGURATION, and two runs under one configuration carry the same version - so comparing a change against the run before it needs this column and cannot be done with that one. NULL for a row written before runs were named.",
        ),
        sa.Column(
            "trace_id",
            sa.Text(),
            nullable=True,
            comment="The OpenTelemetry trace this topic was fitted and labelled in, as 32 hex characters.",
        ),
        sa.Column(
            "span_id",
            sa.Text(),
            nullable=True,
            comment="The span the fit ran in, as 16 hex characters. One span per language, so every topic of one language shares it.",
        ),
        sa.CheckConstraint(
            "question_status IN ('new', 'pending', 'in_progress', 'failed', 'generated')",
            name="topics_question_status_valid",
        ),
        sa.CheckConstraint(
            "status <> 'modelled' OR (topic_index IS NOT NULL AND language IS NOT NULL AND cardinality(top_terms) > 0)",
            name="topics_modelled_is_a_topic",
        ),
        sa.CheckConstraint(
            "status IN ('new', 'pending', 'in_progress', 'failed', 'modelled')",
            name="topics_status_valid",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "language", "topic_index", name="topics_topic_index_unique"
        ),
        comment="Clusters over one language's own vocabulary, factorised out of a tf-idf weighted term matrix. passage_topics carries the membership; facts and questions reach their topics by joining through their passage. Also two queues: a row with a NULL topic_index is a request to refit, and a row that is a topic is a unit of question generation.",
    )
    op.create_index(
        "ix_topics_question_queue",
        "topics",
        ["question_status"],
        unique=False,
        postgresql_where=sa.text("question_status IN ('pending', 'in_progress')"),
    )
    op.create_index(op.f("ix_topics_run_id"), "topics", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_topics_settings_version"),
        "topics",
        ["settings_version"],
        unique=False,
        postgresql_where=sa.text("settings_version IS NOT NULL"),
    )
    op.create_index(op.f("ix_topics_span_id"), "topics", ["span_id"], unique=False)
    op.create_index(op.f("ix_topics_status"), "topics", ["status"], unique=False)
    op.create_index(op.f("ix_topics_trace_id"), "topics", ["trace_id"], unique=False)
    op.create_table(
        "assessments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "artifact_kind",
            sa.Text(),
            nullable=False,
            comment="fact | topic | question. Which of the three foreign keys below is set, stored so the queue can narrow on it and the report can group on it without a CASE over three columns.",
        ),
        sa.Column(
            "fact_id",
            sa.BigInteger(),
            nullable=True,
            comment="The fact this is about, NULL unless artifact_kind is `fact`. Cascades: a judgement about a deleted fact is an opinion about nothing.",
        ),
        sa.Column(
            "topic_id",
            sa.BigInteger(),
            nullable=True,
            comment="The topic this is about, NULL unless artifact_kind is `topic`. A refit replaces every topic, so this cascades on every `make topics-discover`.",
        ),
        sa.Column(
            "question_id",
            sa.BigInteger(),
            nullable=True,
            comment="The question this is about, NULL unless artifact_kind is `question`.",
        ),
        sa.Column(
            "assess_status",
            sa.Text(),
            server_default="new",
            nullable=False,
            comment="This stage's own queue column. A row is enrolled `new` by `start`, which is also what makes it claimable - nothing upstream creates one.",
        ),
        sa.Column(
            "assess_error",
            sa.Text(),
            nullable=True,
            comment="Why the judge could not be asked, NULL when it could.",
        ),
        sa.Column(
            "assess_claimed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When a worker took this row.",
        ),
        sa.Column(
            "assess_trigger",
            sa.Text(),
            nullable=True,
            comment="Which run asked for this artefact to be judged. See `documents.parse_trigger`.",
        ),
        sa.Column(
            "approved",
            sa.Boolean(),
            nullable=True,
            comment="Whether every metric landed on its good side. NULL until the judge has answered, which is most rows until the phase runs. Never read by a gate: `facts.validated` and `questions.status` are what decide whether an artefact is kept, and this is the second opinion recorded beside them.",
        ),
        sa.Column(
            "metrics_due",
            sa.Integer(),
            nullable=True,
            comment="How many metrics this artefact's kind was due under its prompt_version. The judge abstains per metric when the model cannot be reached, so a row with fewer assessment_metrics than this was judged on less than it should have been. Stored rather than derived because the count lives in the source under a version the row outlives. NULL for a row assessed before this column.",
        ),
        sa.Column(
            "judge_model",
            sa.Text(),
            nullable=True,
            comment="The model that judged this, as ASSESSMENT_JUDGE_MODEL named it. Recorded per row because a judge's answers move between models the way a writer's do.",
        ),
        sa.Column(
            "prompt_version",
            sa.Text(),
            nullable=True,
            comment="Version of the judging templates, as assessment.templates.PROMPT_VERSION declares it. Two template versions are two judgements, the same way two extraction prompts are two datasets.",
        ),
        sa.Column(
            "settings_version",
            sa.Text(),
            nullable=True,
            comment="The configuration this judgement was made under, as the digest settings.store computes, or 'environment' when nothing was overridden.",
        ),
        sa.Column(
            "run_id",
            sa.Text(),
            nullable=True,
            comment="Which run judged this row, as `settings.runs.run_id` named it. Two runs of the judge over one corpus compare on this.",
        ),
        sa.Column(
            "trace_id",
            sa.Text(),
            nullable=True,
            comment="The OpenTelemetry trace this judgement was made in, as 32 hex characters. Phoenix resolves a trace from this alone.",
        ),
        sa.Column(
            "span_id",
            sa.Text(),
            nullable=True,
            comment="The span the judge ran in, as 16 hex characters, which is the span this row's annotations hang off in Phoenix's Evaluations view.",
        ),
        sa.Column(
            "assessed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the verdict was reached. NULL exactly when `approved` is.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the row was enrolled, which is when `start` first saw the artefact.",
        ),
        sa.CheckConstraint(
            "(artifact_kind = 'fact') = (fact_id IS NOT NULL) AND (artifact_kind = 'topic') = (topic_id IS NOT NULL) AND (artifact_kind = 'question') = (question_id IS NOT NULL)",
            name="assessments_kind_agrees",
        ),
        sa.CheckConstraint(
            "artifact_kind IN ('fact', 'topic', 'question')",
            name="assessments_kind_valid",
        ),
        sa.CheckConstraint(
            "assess_status IN ('new', 'pending', 'in_progress', 'failed', 'assessed')",
            name="assessments_status_valid",
        ),
        sa.CheckConstraint(
            "(approved IS NULL) = (assessed_at IS NULL)",
            name="assessments_verdict_together",
        ),
        sa.CheckConstraint(
            "(fact_id IS NOT NULL)::int + (topic_id IS NOT NULL)::int + (question_id IS NOT NULL)::int = 1",
            name="assessments_one_artifact",
        ),
        sa.ForeignKeyConstraint(["fact_id"], ["facts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fact_id", name="assessments_one_per_fact"),
        sa.UniqueConstraint("question_id", name="assessments_one_per_question"),
        sa.UniqueConstraint("topic_id", name="assessments_one_per_topic"),
        comment="What an LLM judge made of one fact, topic or question, and the queue that asked it. Never a gate: the checker and the gates decide what is kept, and this is recorded beside their verdict so the two can be compared. One metric row per judgement is in assessment_metrics.",
    )
    op.create_index(
        "ix_assessments_approved",
        "assessments",
        ["approved"],
        unique=False,
        postgresql_where=sa.text("approved IS NOT NULL"),
    )
    op.create_index(
        "ix_assessments_kind", "assessments", ["artifact_kind"], unique=False
    )
    op.create_index(
        "ix_assessments_queue",
        "assessments",
        ["assess_status"],
        unique=False,
        postgresql_where=sa.text("assess_status IN ('pending', 'in_progress')"),
    )
    op.create_index(
        op.f("ix_assessments_run_id"), "assessments", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_assessments_settings_version"),
        "assessments",
        ["settings_version"],
        unique=False,
    )
    op.create_table(
        "ingest_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "submitted_filename",
            sa.Text(),
            nullable=False,
            comment="Filename as submitted. The earliest stored event for a hash is that document's original filename.",
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the upload was received.",
        ),
        sa.Column(
            "size_bytes",
            sa.BigInteger(),
            nullable=False,
            comment="Size of the submitted file.",
        ),
        sa.Column(
            "sha256",
            sa.CHAR(length=64),
            nullable=True,
            comment="SHA-256 of the submitted bytes, and the link to the document they became. NULL for uploads refused before hashing, which is why the foreign key tolerates NULL.",
        ),
        sa.Column(
            "outcome",
            sa.Text(),
            nullable=False,
            comment="stored | duplicate_bytes | too_large | unsupported_type. Enforced by a CHECK constraint.",
        ),
        sa.Column(
            "detail",
            sa.Text(),
            nullable=True,
            comment="Human-readable reason, shown to the uploader when a file is refused.",
        ),
        sa.CheckConstraint(
            "outcome IN ('stored', 'duplicate_bytes', 'too_large', 'unsupported_type')",
            name="ingest_events_outcome_valid",
        ),
        sa.ForeignKeyConstraint(["sha256"], ["documents.sha256"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        comment="Every upload attempt, including refused ones. A refused upload writes nothing to documents, so this is the only record that it happened. Also holds ingest provenance: the same bytes arriving three times under three names is one documents row and three rows here.",
    )
    op.create_table(
        "passages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "doc_sha256",
            sa.CHAR(length=64),
            nullable=False,
            comment="The document this passage was cut from.",
        ),
        sa.Column(
            "ordinal",
            sa.Integer(),
            nullable=False,
            comment="Position in reading order within the document, from 1 and contiguous, so ordinal +/- 1 are the neighbouring passages. Reassigned on every re-chunk.",
        ),
        sa.Column(
            "extract_status",
            sa.Text(),
            server_default="new",
            nullable=False,
            comment="new | pending | in_progress | extracted | failed. Extraction queues over passages rather than documents, which is the unit that divides evenly between workers.",
        ),
        sa.Column(
            "extract_error",
            sa.Text(),
            nullable=True,
            comment="Why this passage could not be read.",
        ),
        sa.Column(
            "extract_claimed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When a worker claimed this passage, NULL when none holds it.",
        ),
        sa.Column(
            "extract_trigger",
            sa.Text(),
            nullable=True,
            comment="Which run asked for this passage to be read. See `documents.parse_trigger`.",
        ),
        sa.Column(
            "text",
            sa.Text(),
            nullable=False,
            comment="The passage content. The evidence offsets in fact_passages are relative to this string.",
        ),
        sa.Column(
            "language",
            sa.CHAR(length=2),
            nullable=True,
            comment="ISO 639-1, detected on this passage rather than inherited from the document: one file carries a German report and its English summary, so a document-wide label reads half the passages with the wrong pipeline. Selects the spaCy pipeline, and partitions the topic model. NULL when the passage was too short to tell.",
        ),
        sa.Column(
            "sentences",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
            comment="The sentences spaCy found, [{i, start, end, predicates}], with offsets into text. Extraction cites one by index, so a citation needs no quote to search for. NULL until chunking has run under a version that writes it.",
        ),
        sa.Column(
            "lemmas",
            postgresql.ARRAY(sa.Text()),
            nullable=True,
            comment="Content lemmas, the vocabulary topic modelling is fitted over. Written here so one segmentation serves both stages and a fit reads a column instead of re-tokenising the corpus.",
        ),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1024),
            nullable=True,
            comment="Passage embedding, in the same space as facts.embedding and questions.embedding. What a nearest-passage search reads. Written by extraction rather than by chunking, which owns every other column here: the extraction worker loads the model anyway for the fact dedup gate, and a second worker loading two gigabytes to write one column is the cost this avoids. NULL until a passage has been through extraction under a deployment that embeds.",
        ),
        sa.Column(
            "page_from",
            sa.Integer(),
            nullable=True,
            comment="Page the passage starts on.",
        ),
        sa.Column(
            "page_to", sa.Integer(), nullable=True, comment="Page the passage ends on."
        ),
        sa.Column(
            "section_path",
            sa.Text(),
            nullable=True,
            comment='Heading trail, for example "3 > 3.2 > Delivery".',
        ),
        sa.Column(
            "block_type",
            sa.Text(),
            nullable=True,
            comment="Docling's DocItemLabel for the source item. Routes extraction: a table goes to the cell reader, everything else to the model. A passage holding items of several kinds is labelled table if any of them is one.",
        ),
        sa.Column(
            "doc_item_refs",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            comment="The converter's identifiers for the items this passage was cut from, and the only non-fuzzy way back to the converted document.",
        ),
        sa.Column(
            "bbox",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
            comment="Where the passage sits, one box per page it spans: [{page, l, t, r, b}], on a top-left origin. NULL when the converter recorded no position.",
        ),
        sa.Column(
            "table_cells",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
            comment="The cell grids behind a table passage: [{caption, num_rows, num_cols, cells:[{row, col, row_span, col_span, column_header, row_header, text, line}]}]. `line` is the rendered Markdown row the cell sits in and the evidence a fact drawn from it cites; NULL on a header cell. Only the rows this passage renders are kept. NULL unless block_type is table.",
        ),
        sa.Column(
            "run_id",
            sa.Text(),
            nullable=True,
            comment="Which run chunked this passage out of its document, as `settings.runs.run_id` named it.",
        ),
        sa.Column(
            "trace_id",
            sa.Text(),
            nullable=True,
            comment="The OpenTelemetry trace this passage was chunked in, as 32 hex characters.",
        ),
        sa.Column(
            "span_id",
            sa.Text(),
            nullable=True,
            comment="The span the chunking ran in, as 16 hex characters. One span per document, so every passage of one document shares it.",
        ),
        sa.CheckConstraint(
            "extract_status IN ('new', 'pending', 'in_progress', 'failed', 'extracted')",
            name="passages_extract_status_valid",
        ),
        sa.CheckConstraint(
            "language IS NULL OR language ~ '^[a-z]{2}$'",
            name="passages_language_is_iso_639_1",
        ),
        sa.CheckConstraint("ordinal > 0", name="passages_ordinal_positive"),
        sa.ForeignKeyConstraint(
            ["doc_sha256"], ["documents.sha256"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doc_sha256", "ordinal"),
        comment="A document split into retrievable chunks. Immutable: re-chunking deletes and re-inserts every passage of a document.",
    )
    op.create_index(
        "ix_passages_embedding_hnsw",
        "passages",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_passages_extract_queue",
        "passages",
        ["id"],
        unique=False,
        postgresql_where=sa.text("extract_status IN ('pending', 'in_progress')"),
    )
    op.create_index(
        op.f("ix_passages_language"), "passages", ["language"], unique=False
    )
    op.create_index(
        "ix_passages_lemmas_gin",
        "passages",
        ["lemmas"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_passages_run_id"), "passages", ["run_id"], unique=False)
    op.create_index(op.f("ix_passages_span_id"), "passages", ["span_id"], unique=False)
    op.create_index(
        "ix_passages_text_trgm",
        "passages",
        ["text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"text": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_passages_trace_id"), "passages", ["trace_id"], unique=False
    )
    op.create_table(
        "question_facts",
        sa.Column(
            "question_id", sa.BigInteger(), nullable=False, comment="The question."
        ),
        sa.Column(
            "fact_id",
            sa.BigInteger(),
            nullable=False,
            comment="A fact the question tests. Deleting the fact removes this row; see the note on the questions table about questions left with no facts.",
        ),
        sa.ForeignKeyConstraint(["fact_id"], ["facts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("question_id", "fact_id"),
        comment="Which facts a question was generated from. One row for an ordinary question, two or more for a cross-document question. The passages a question needs retrieved are derived from here through fact_passages rather than stored separately.",
    )
    op.create_index(
        op.f("ix_question_facts_fact_id"), "question_facts", ["fact_id"], unique=False
    )
    op.create_table(
        "assessment_metrics",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "assessment_id",
            sa.BigInteger(),
            nullable=False,
            comment="The assessment this metric belongs to.",
        ),
        sa.Column(
            "metric",
            sa.Text(),
            nullable=False,
            comment="hallucination | relevance | qa_correctness | summarization. Spelled as arize-phoenix-evals spells it.",
        ),
        sa.Column(
            "label",
            sa.Text(),
            nullable=False,
            comment="What the judge answered, as one of that metric's own labels - `factual` or `hallucinated`, `relevant` or `unrelated`, and so on. The word rather than the number, because that is what Phoenix's Evaluations view groups by.",
        ),
        sa.Column(
            "score",
            sa.Float(),
            nullable=False,
            comment="The score that label carries, as phoenix-evals scores it. Note the direction is the metric's: `hallucination` scores 1.0 for `hallucinated` because its optimisation direction is minimise, and every other metric here scores 1.0 for its good label.",
        ),
        sa.Column(
            "approved",
            sa.Boolean(),
            nullable=False,
            comment="Whether this label is the good side of this metric. Stored rather than derived from the score, because the score's direction differs per metric and a reader summing scores across metrics would be adding a hallucination rate to a relevance rate.",
        ),
        sa.Column(
            "explanation",
            sa.Text(),
            server_default="",
            nullable=False,
            comment="Why the judge said so, in its own words. Asked for in the same call as the label: an unexplained verdict is one a reviewer cannot act on, and the queue this feeds is for people.",
        ),
        sa.CheckConstraint(
            "metric IN ('hallucination', 'relevance', 'qa_correctness', 'summarization', 'toxicity', 'conciseness', 'refusal')",
            name="assessment_metrics_metric_valid",
        ),
        sa.CheckConstraint(
            "score >= 0 AND score <= 1", name="assessment_metrics_score_in_range"
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["assessments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "assessment_id", "metric", name="assessment_metrics_one_per_metric"
        ),
        comment="One metric of one assessment: what the judge called it, the score that label carries, and why. The names, the labels and the scores are arize-phoenix-evals', so a reader who knows `hallucination` there knows what this column holds.",
    )
    op.create_index(
        op.f("ix_assessment_metrics_assessment_id"),
        "assessment_metrics",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        "ix_assessment_metrics_metric", "assessment_metrics", ["metric"], unique=False
    )
    op.create_table(
        "fact_passages",
        sa.Column("fact_id", sa.BigInteger(), nullable=False, comment="The fact."),
        sa.Column(
            "passage_id",
            sa.BigInteger(),
            nullable=False,
            comment="A passage the claim rests on. Deleting the passage deletes this row and the fact with it.",
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
            comment="Where this passage sat in what the model was shown, from 0. 0 for the one passage of an atomic fact, a summary or an outline.",
        ),
        sa.Column(
            "sentence_ids",
            postgresql.ARRAY(sa.Integer()),
            nullable=True,
            comment="Which of this passage's sentences the claim rests on. NULL when the claim named no sentence this passage has: a refused fact, or a bridge drawn before prompt version 2. Neither is offered to question generation.",
        ),
        sa.Column(
            "evidence_start",
            sa.Integer(),
            nullable=True,
            comment="Offset of the cited span's first character within this passage's text. NULL alongside sentence_ids.",
        ),
        sa.Column(
            "evidence_end",
            sa.Integer(),
            nullable=True,
            comment="Offset one past its last character.",
        ),
        sa.CheckConstraint(
            "(sentence_ids IS NULL AND evidence_start IS NULL AND evidence_end IS NULL) OR (sentence_ids IS NOT NULL AND evidence_end >= evidence_start)",
            name="fact_passages_citation_complete",
        ),
        sa.ForeignKeyConstraint(["fact_id"], ["facts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["passage_id"], ["passages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("fact_id", "passage_id"),
        comment="Which passages a fact rests on and where in each, one row per passage for every kind. The only route from a fact to a passage.",
    )
    op.create_index(
        op.f("ix_fact_passages_passage_id"),
        "fact_passages",
        ["passage_id"],
        unique=False,
    )
    op.create_table(
        "passage_topics",
        sa.Column(
            "passage_id",
            sa.BigInteger(),
            nullable=False,
            comment="The passage. Re-chunking deletes it and these rows with it, which is what leaves a fit stale.",
        ),
        sa.Column("topic_id", sa.BigInteger(), nullable=False, comment="The topic."),
        sa.Column(
            "weight",
            sa.Float(),
            nullable=False,
            comment="Share of this passage attributed to this topic, in (0, 1]. The weights for one passage sum to at most 1, which spans rows and so is not enforced; the only writer is the topic model.",
        ),
        sa.CheckConstraint(
            "weight > 0 AND weight <= 1", name="passage_topics_weight_is_a_probability"
        ),
        sa.ForeignKeyConstraint(["passage_id"], ["passages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("passage_id", "topic_id"),
        comment="The topic distribution, one row per passage-topic pair above the weight floor. The only place the relationship is stored; the dominant topic is the highest weight, derived rather than stored.",
    )
    op.create_index(
        "ix_passage_topics_weight",
        "passage_topics",
        ["passage_id", "weight"],
        unique=False,
    )
    # ### end Alembic commands ###

    for statement in _FUNCTIONS:
        op.execute(statement)
    for table in _ARCHIVED:
        op.execute(
            f"CREATE TRIGGER {table}_archive_deleted_row AFTER DELETE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION archive_deleted_row()"
        )
    op.execute(
        "CREATE TRIGGER fact_passages_delete_orphan_fact AFTER DELETE ON fact_passages "
        "FOR EACH ROW EXECUTE FUNCTION delete_fact_without_passage()"
    )
    op.execute(
        "CREATE TRIGGER question_facts_delete_orphan_question AFTER DELETE ON question_facts "
        "FOR EACH ROW EXECUTE FUNCTION delete_question_without_facts()"
    )


def downgrade() -> None:
    """Takes it back out."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_passage_topics_weight", table_name="passage_topics")
    op.drop_table("passage_topics")
    op.drop_index(op.f("ix_fact_passages_passage_id"), table_name="fact_passages")
    op.drop_table("fact_passages")
    op.drop_index("ix_assessment_metrics_metric", table_name="assessment_metrics")
    op.drop_index(
        op.f("ix_assessment_metrics_assessment_id"), table_name="assessment_metrics"
    )
    op.drop_table("assessment_metrics")
    op.drop_index(op.f("ix_question_facts_fact_id"), table_name="question_facts")
    op.drop_table("question_facts")
    op.drop_index(op.f("ix_passages_trace_id"), table_name="passages")
    op.drop_index(
        "ix_passages_text_trgm",
        table_name="passages",
        postgresql_using="gin",
        postgresql_ops={"text": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_passages_span_id"), table_name="passages")
    op.drop_index(op.f("ix_passages_run_id"), table_name="passages")
    op.drop_index(
        "ix_passages_lemmas_gin", table_name="passages", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_passages_language"), table_name="passages")
    op.drop_index(
        "ix_passages_extract_queue",
        table_name="passages",
        postgresql_where=sa.text("extract_status IN ('pending', 'in_progress')"),
    )
    op.drop_index(
        "ix_passages_embedding_hnsw",
        table_name="passages",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("passages")
    op.drop_table("ingest_events")
    op.drop_index(op.f("ix_assessments_settings_version"), table_name="assessments")
    op.drop_index(op.f("ix_assessments_run_id"), table_name="assessments")
    op.drop_index(
        "ix_assessments_queue",
        table_name="assessments",
        postgresql_where=sa.text("assess_status IN ('pending', 'in_progress')"),
    )
    op.drop_index("ix_assessments_kind", table_name="assessments")
    op.drop_index(
        "ix_assessments_approved",
        table_name="assessments",
        postgresql_where=sa.text("approved IS NOT NULL"),
    )
    op.drop_table("assessments")
    op.drop_index(op.f("ix_topics_trace_id"), table_name="topics")
    op.drop_index(op.f("ix_topics_status"), table_name="topics")
    op.drop_index(op.f("ix_topics_span_id"), table_name="topics")
    op.drop_index(op.f("ix_topics_settings_version"), table_name="topics")
    op.drop_index(op.f("ix_topics_run_id"), table_name="topics")
    op.drop_index(
        "ix_topics_question_queue",
        table_name="topics",
        postgresql_where=sa.text("question_status IN ('pending', 'in_progress')"),
    )
    op.drop_table("topics")
    op.drop_index(op.f("ix_service_settings_service"), table_name="service_settings")
    op.drop_table("service_settings")
    op.drop_index(op.f("ix_questions_trace_id"), table_name="questions")
    op.drop_index("ix_questions_status", table_name="questions")
    op.drop_index(op.f("ix_questions_span_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_settings_version"), table_name="questions")
    op.drop_index(op.f("ix_questions_run_id"), table_name="questions")
    op.drop_index(
        "ix_questions_reviewed_verdict",
        table_name="questions",
        postgresql_where=sa.text("reviewed_verdict IS NOT NULL"),
    )
    op.drop_index(op.f("ix_questions_release_id"), table_name="questions")
    op.drop_index("ix_questions_question_type", table_name="questions")
    op.drop_index(op.f("ix_questions_prompt_version"), table_name="questions")
    op.drop_index("ix_questions_follows_id", table_name="questions")
    op.drop_index(
        "ix_questions_embedding_hnsw",
        table_name="questions",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(
        "ix_questions_confidence",
        table_name="questions",
        postgresql_where=sa.text("confidence IS NOT NULL"),
    )
    op.drop_table("questions")
    op.drop_index(op.f("ix_prompts_version"), table_name="prompts")
    op.drop_index(op.f("ix_prompts_service"), table_name="prompts")
    op.drop_table("prompts")
    op.drop_index(op.f("ix_facts_trace_id"), table_name="facts")
    op.drop_index(
        "ix_facts_statement_trgm",
        table_name="facts",
        postgresql_using="gin",
        postgresql_ops={"statement": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_facts_span_id"), table_name="facts")
    op.drop_index(op.f("ix_facts_settings_version"), table_name="facts")
    op.drop_index(op.f("ix_facts_run_id"), table_name="facts")
    op.drop_index(
        "ix_facts_reviewed_verdict",
        table_name="facts",
        postgresql_where=sa.text("reviewed_verdict IS NOT NULL"),
    )
    op.drop_index("ix_facts_rejection_code", table_name="facts")
    op.drop_index("ix_facts_kind", table_name="facts")
    op.drop_index(
        "ix_facts_evidence_trgm",
        table_name="facts",
        postgresql_using="gin",
        postgresql_ops={"evidence_text": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_facts_embedding_hnsw",
        table_name="facts",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(
        "ix_facts_confidence",
        table_name="facts",
        postgresql_where=sa.text("confidence IS NOT NULL"),
    )
    op.drop_table("facts")
    op.drop_index(op.f("ix_documents_parse_trace_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_parse_span_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_parse_run_id"), table_name="documents")
    op.drop_index(
        "ix_documents_parse_queue",
        table_name="documents",
        postgresql_where=sa.text("parse_status IN ('pending', 'in_progress')"),
    )
    op.drop_index(
        "ix_documents_chunk_queue",
        table_name="documents",
        postgresql_where=sa.text("chunk_status IN ('pending', 'in_progress')"),
    )
    op.drop_table("documents")
    op.drop_index("ix_archived_rows_table_name", table_name="archived_rows")
    op.drop_index("ix_archived_rows_archived_at", table_name="archived_rows")
    op.drop_table("archived_rows")
    # ### end Alembic commands ###

    # The triggers went with the tables they sit on; the functions did not.
    for function in (
        "archive_deleted_row",
        "delete_fact_without_passage",
        "delete_question_without_facts",
    ):
        op.execute(f"DROP FUNCTION IF EXISTS {function}()")
