"""One embedding model sizes and embeds; chunking drops nothing.

Revision: eccb9f1cd7d5
Parent:   5ada5ee19fce
Created:  2026-09-12 13:55:00.373247
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision: str = "eccb9f1cd7d5"
down_revision: str | None = "5ada5ee19fce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Applies the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "oversized",
            sa.Integer(),
            nullable=True,
            comment="Passages the last chunking run stored above EMBEDDING_MAX_TOKENS. Expected to be 0: the chunker splits on that same budget, so anything above it means the split did not happen, and the passage will be truncated when it is embedded. A tripwire, not a size policy - chunking discards nothing. It replaced a pair of character counts that recorded what a character ceiling had thrown away, which is how whole tables came to reach no passage and no fact while the document still read as cleanly chunked.",
        ),
    )
    op.alter_column(
        "documents",
        "content_sha256",
        existing_type=sa.CHAR(length=64),
        comment='SHA-256 of the body text - table cell values included - with page_header and page_footer blocks removed, so a re-export of the same page hashes identically despite different bytes while two revisions of a table differing only in their numbers do not. Only parsing can produce it, because only Docling classifies blocks by layout. Nothing acts on it at ingest; it answers "do we already have this content?" on request.',
        existing_comment='SHA-256 of the body text - table cell values included - with page_header and page_footer blocks removed, so a re-export of the same page hashes identically despite different bytes while two fee schedules differing only in their numbers do not. Only parsing can produce it, because only Docling classifies blocks by layout. Nothing acts on it at ingest; it answers "do we already have this content?" on request.',
        existing_nullable=True,
    )
    op.drop_column("documents", "dropped_short")
    op.drop_column("documents", "dropped_long")
    op.alter_column(
        "passages",
        "section_path",
        existing_type=sa.TEXT(),
        comment='Heading trail, for example "3 > 3.2 > Delivery". What a reviewer reads to orient themselves.',
        existing_comment='Heading trail, for example "3 > 3.2 > Fees". What a reviewer reads to orient themselves.',
        existing_nullable=True,
    )
    op.alter_column(
        "questions",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
        comment="Question embedding, used by the semantic dedup and unanswerability gates. Those do cosine search over every accepted question, which the HNSW index above serves. 1024 dimensions because that is the width of EMBEDDING_MODEL, which is also the tokenizer chunking sizes a passage by - one name in .env for both, so a passage cannot be sized against one model and embedded by another. Changing that model means a migration here and re-embedding every row; pgvector indexes HNSW up to 2000 dimensions, so a wider model than that must be truncated, which Matryoshka training supports.",
        existing_comment="Question embedding, used by the semantic dedup and unanswerability gates. Those do cosine search over every accepted question and will need an HNSW index before they are usable at scale. 768 dimensions because that is what most open embedding models emit - nomic-embed-text, bge-base, e5-base, all-mpnet-base-v2, gte-base. A model with a wider native output, such as Qwen3-Embedding at 4096, must be truncated to fit, which its Matryoshka training supports.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "label",
        existing_type=sa.TEXT(),
        comment="Name assigned by a person, if any, so reports read a subject rather than a list of terms. Carried across a refit by matching top terms, which is the only signature there is; a topic whose terms have moved too far loses it.",
        existing_comment='Name assigned by a person, if any, so reports read "Account fees" rather than a list of terms. Carried across a refit by matching top terms, which is the only signature there is; a topic whose terms have moved too far loses it.',
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Takes it back out."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "topics",
        "label",
        existing_type=sa.TEXT(),
        comment='Name assigned by a person, if any, so reports read "Account fees" rather than a list of terms. Carried across a refit by matching top terms, which is the only signature there is; a topic whose terms have moved too far loses it.',
        existing_comment="Name assigned by a person, if any, so reports read a subject rather than a list of terms. Carried across a refit by matching top terms, which is the only signature there is; a topic whose terms have moved too far loses it.",
        existing_nullable=True,
    )
    op.alter_column(
        "questions",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        comment="Question embedding, used by the semantic dedup and unanswerability gates. Those do cosine search over every accepted question and will need an HNSW index before they are usable at scale. 768 dimensions because that is what most open embedding models emit - nomic-embed-text, bge-base, e5-base, all-mpnet-base-v2, gte-base. A model with a wider native output, such as Qwen3-Embedding at 4096, must be truncated to fit, which its Matryoshka training supports.",
        existing_comment="Question embedding, used by the semantic dedup and unanswerability gates. Those do cosine search over every accepted question, which the HNSW index above serves. 1024 dimensions because that is the width of EMBEDDING_MODEL, which is also the tokenizer chunking sizes a passage by - one name in .env for both, so a passage cannot be sized against one model and embedded by another. Changing that model means a migration here and re-embedding every row; pgvector indexes HNSW up to 2000 dimensions, so a wider model than that must be truncated, which Matryoshka training supports.",
        existing_nullable=True,
    )
    op.alter_column(
        "passages",
        "section_path",
        existing_type=sa.TEXT(),
        comment='Heading trail, for example "3 > 3.2 > Fees". What a reviewer reads to orient themselves.',
        existing_comment='Heading trail, for example "3 > 3.2 > Delivery". What a reviewer reads to orient themselves.',
        existing_nullable=True,
    )
    op.add_column(
        "documents",
        sa.Column(
            "dropped_long",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Chunks the last run discarded for exceeding CHUNKING_MAX_CHARS, typically one large unsplittable table. Counted for the same reason as dropped_short.",
        ),
    )
    op.add_column(
        "documents",
        sa.Column(
            "dropped_short",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment='Chunks the last run discarded for falling under CHUNKING_MIN_CHARS. Stored rather than logged, because it is content that reached no passage and no fact: "which documents lost content to the size bounds?" is otherwise unanswerable from the database.',
        ),
    )
    op.alter_column(
        "documents",
        "content_sha256",
        existing_type=sa.CHAR(length=64),
        comment='SHA-256 of the body text - table cell values included - with page_header and page_footer blocks removed, so a re-export of the same page hashes identically despite different bytes while two fee schedules differing only in their numbers do not. Only parsing can produce it, because only Docling classifies blocks by layout. Nothing acts on it at ingest; it answers "do we already have this content?" on request.',
        existing_comment='SHA-256 of the body text - table cell values included - with page_header and page_footer blocks removed, so a re-export of the same page hashes identically despite different bytes while two revisions of a table differing only in their numbers do not. Only parsing can produce it, because only Docling classifies blocks by layout. Nothing acts on it at ingest; it answers "do we already have this content?" on request.',
        existing_nullable=True,
    )
    op.drop_column("documents", "oversized")
    # ### end Alembic commands ###
