"""One topic model per language.

A passage now carries the language it is written in, detected on the passage
rather than inherited from its document, and each language is fitted its own
LDA model over its own vocabulary. The stored topics were fitted over one
vocabulary spanning both and belong to no language, so they are deleted;
chunking is queued again, because chunking is what detects a passage's
language

Revision: 5d97bffee5f1
Parent:   84e55e02db3e
Created:  2026-09-12 22:58:47.342225
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5d97bffee5f1"
down_revision: str | None = "84e55e02db3e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Applies the change."""
    # Before the constraints below: the stored topics were fitted over one
    # vocabulary spanning every language and cannot be assigned to one, and
    # `topics_modelled_is_a_topic` is about to require that they are.
    op.execute("DELETE FROM topics")
    # Chunking is what detects a passage's language, so passages need reading
    # again before any model can be fitted.
    op.execute(
        "UPDATE documents SET chunk_status = 'new', chunk_error = NULL, "
        "chunk_claimed_at = NULL WHERE chunk_status <> 'new'"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "passages",
        sa.Column(
            "language",
            sa.CHAR(length=2),
            nullable=True,
            comment="ISO 639-1, detected on this passage rather than inherited from the document: one file carries a German report and its English summary, so a document-wide label reads half the passages with the wrong pipeline. Selects the spaCy pipeline, and partitions the topic model. NULL when the passage was too short to tell.",
        ),
    )
    op.create_index(
        op.f("ix_passages_language"), "passages", ["language"], unique=False
    )
    op.add_column(
        "topics",
        sa.Column(
            "language",
            sa.CHAR(length=2),
            nullable=True,
            comment="Which language's model this topic belongs to. Each language is fitted separately over its own vocabulary, because one model across both spends topics on telling the languages apart rather than on telling subjects apart. NULL on a fit request.",
        ),
    )
    op.alter_column(
        "topics",
        "topic_index",
        existing_type=sa.INTEGER(),
        comment="Position of this topic in its language's fitted model, and the key scoring a passage returns. Unique per language, not overall. NULL means this row is a fit request rather than a topic.",
        existing_comment="Position of this topic in the fitted model, and the key scoring a passage returns. NULL means this row is a fit request rather than a topic; NULLs do not collide under a unique constraint.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "corpus_passages",
        existing_type=sa.INTEGER(),
        comment="How many passages of this language the model was fitted over. Compared against the live count to tell whether the topics still describe the corpus.",
        existing_comment="How many passages the model was fitted over. Compared against the live count to tell whether the topics still describe the corpus.",
        existing_nullable=True,
    )
    op.drop_constraint(op.f("topics_topic_index_unique"), "topics", type_="unique")
    op.create_unique_constraint(
        "topics_topic_index_unique", "topics", ["language", "topic_index"]
    )
    # ### end Alembic commands ###

    # Autogenerate does not compare CHECK constraints, so both are written out.
    op.create_check_constraint(
        "passages_language_is_iso_639_1",
        "passages",
        "language IS NULL OR language ~ '^[a-z]{2}$'",
    )
    op.drop_constraint("topics_modelled_is_a_topic", "topics", type_="check")
    op.create_check_constraint(
        "topics_modelled_is_a_topic",
        "topics",
        "status <> 'modelled' OR (topic_index IS NOT NULL AND "
        "language IS NOT NULL AND cardinality(top_terms) > 0)",
    )
    op.create_table_comment(
        "topics",
        "Clusters over one language's own vocabulary, factorised out of a tf-idf weighted term matrix. passage_topics carries the membership; facts and questions reach their topics by joining through their passage. Also the queue: a row with a NULL topic_index is a request to refit.",
        existing_comment="Clusters over the corpus's own vocabulary, fitted by LDA. passage_topics carries the membership; facts and questions reach their topics by joining through their passage. Also the queue: a row with a NULL topic_index is a request to refit.",
    )
    op.create_table_comment(
        "passage_topics",
        "The topic distribution, one row per passage-topic pair above the weight floor. The only place the relationship is stored; the dominant topic is the highest weight, derived rather than stored.",
        existing_comment="The LDA distribution, one row per passage-topic pair above the weight floor. The only place the relationship is stored; the dominant topic is the highest weight, derived rather than stored.",
    )


def downgrade() -> None:
    """Takes it back out.

    The topics deleted on the way up do not come back: the column saying
    which language each belongs to is dropped below.
    """
    op.execute("DELETE FROM topics")
    op.create_table_comment(
        "topics",
        "Clusters over the corpus's own vocabulary, fitted by LDA. passage_topics carries the membership; facts and questions reach their topics by joining through their passage. Also the queue: a row with a NULL topic_index is a request to refit.",
        existing_comment="Clusters over one language's own vocabulary, factorised out of a tf-idf weighted term matrix. passage_topics carries the membership; facts and questions reach their topics by joining through their passage. Also the queue: a row with a NULL topic_index is a request to refit.",
    )
    op.create_table_comment(
        "passage_topics",
        "The LDA distribution, one row per passage-topic pair above the weight floor. The only place the relationship is stored; the dominant topic is the highest weight, derived rather than stored.",
        existing_comment="The topic distribution, one row per passage-topic pair above the weight floor. The only place the relationship is stored; the dominant topic is the highest weight, derived rather than stored.",
    )
    op.drop_constraint("topics_modelled_is_a_topic", "topics", type_="check")
    op.create_check_constraint(
        "topics_modelled_is_a_topic",
        "topics",
        "status <> 'modelled' OR "
        "(topic_index IS NOT NULL AND cardinality(top_terms) > 0)",
    )
    op.drop_constraint("passages_language_is_iso_639_1", "passages", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("topics_topic_index_unique", "topics", type_="unique")
    op.create_unique_constraint(
        op.f("topics_topic_index_unique"),
        "topics",
        ["topic_index"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "topics",
        "corpus_passages",
        existing_type=sa.INTEGER(),
        comment="How many passages the model was fitted over. Compared against the live count to tell whether the topics still describe the corpus.",
        existing_comment="How many passages of this language the model was fitted over. Compared against the live count to tell whether the topics still describe the corpus.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "topic_index",
        existing_type=sa.INTEGER(),
        comment="Position of this topic in the fitted model, and the key scoring a passage returns. NULL means this row is a fit request rather than a topic; NULLs do not collide under a unique constraint.",
        existing_comment="Position of this topic in its language's fitted model, and the key scoring a passage returns. Unique per language, not overall. NULL means this row is a fit request rather than a topic.",
        existing_nullable=True,
    )
    op.drop_column("topics", "language")
    op.drop_index(op.f("ix_passages_language"), table_name="passages")
    op.drop_column("passages", "language")
    # ### end Alembic commands ###
