"""Record what named a topic.

Revision: 29b6c8dff20e
Parent:   5d97bffee5f1
Created:  2026-09-13 09:22:03.421306
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "29b6c8dff20e"
down_revision: str | None = "5d97bffee5f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Applies the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "topics",
        sa.Column(
            "labelled_by",
            sa.Text(),
            nullable=True,
            comment="What named it: 'person', or the model identifier. A name a person typed is never overwritten by a model's, and a report that reads by name should say which it is reading.",
        ),
    )
    op.alter_column(
        "topics",
        "label",
        existing_type=sa.TEXT(),
        comment="The subject this topic is, in words.",
        existing_comment="Name assigned by a person, if any.",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Takes it back out."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "topics",
        "label",
        existing_type=sa.TEXT(),
        comment="Name assigned by a person, if any.",
        existing_comment="The subject this topic is, in words.",
        existing_nullable=True,
    )
    op.drop_column("topics", "labelled_by")
    # ### end Alembic commands ###
