"""Cite a sentence, check a claim with spaCy.

A fact now cites a numbered sentence of its passage instead of quoting one,
and is checked on its parse instead of on how many words it shares with its
source. Neither the citation nor the checks can be derived from what is
stored, so every existing fact is deleted and its passage returned to the
queue; passages are returned to chunking, which is what writes the sentences
a citation names.

Revision: 84e55e02db3e
Parent:   eccb9f1cd7d5
Created:  2026-09-12 18:42:58.587297
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "84e55e02db3e"
down_revision: str | None = "eccb9f1cd7d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Applies the change."""
    # Before the columns below are added NOT NULL: no stored fact carries a
    # sentence id or a parse, and neither can be reconstructed. Re-chunking is
    # what writes passages.sentences, so chunking is queued again too.
    op.execute("DELETE FROM facts")
    op.execute(
        "UPDATE passages SET extract_status = 'new', extract_error = NULL, "
        "extract_claimed_at = NULL WHERE extract_status <> 'new'"
    )
    op.execute(
        "UPDATE documents SET chunk_status = 'new', chunk_error = NULL, "
        "chunk_claimed_at = NULL WHERE chunk_status <> 'new'"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents",
        "sha256",
        existing_type=sa.CHAR(length=64),
        comment="SHA-256 of the raw file bytes, and the object key in both buckets: documents/{sha[0:2]}/{sha[2:4]}/{sha}.{ext} and parsed/.../{sha}.json. Both keys are derived in code, never stored.",
        existing_comment="SHA-256 of the raw file bytes. Primary key, and the object key in both buckets: documents/{sha[0:2]}/{sha[2:4]}/{sha} with the extension mime_type implies, and parsed/.../{sha}.json. The 2x2-hex fanout keeps the SeaweedFS filer off a single hot directory. Both keys are derived in code, never stored.",
        existing_nullable=False,
    )
    op.alter_column(
        "documents",
        "mime_type",
        existing_type=sa.TEXT(),
        comment="Detected from the leading bytes at upload.",
        existing_comment="Detected from the leading bytes at upload. The type declared by the upload form is ignored.",
        existing_nullable=False,
    )
    op.alter_column(
        "documents",
        "char_count",
        existing_type=sa.INTEGER(),
        comment="Extractable characters, counted by PyMuPDF at upload.",
        existing_comment="Extractable characters, counted by PyMuPDF at upload. Zero suggests a scanned document.",
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "language",
        existing_type=sa.CHAR(length=2),
        comment="ISO 639-1, NULL until parsing detects it. Selects the spaCy pipeline chunking and extraction read this document with.",
        existing_comment="ISO 639-1, NULL until parsing detects it. Constrained to the shape of a code, not to a list of them: which languages the corpus holds is PARSING_LANGUAGES, and the detector can only answer from that set. Note the OCR configuration uses 639-2 codes instead.",
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "content_sha256",
        existing_type=sa.CHAR(length=64),
        comment='SHA-256 of the body text with whitespace collapsed and case folded. Answers "do we already have this content?" on request; nothing acts on it at ingest.',
        existing_comment='SHA-256 of the body text - table cell values included - with page_header and page_footer blocks removed, so a re-export of the same page hashes identically despite different bytes while two revisions of a table differing only in their numbers do not. Only parsing can produce it, because only Docling classifies blocks by layout. Nothing acts on it at ingest; it answers "do we already have this content?" on request.',
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "parse_confidence",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Mean confidence the parser reported, in [0, 1].",
        existing_comment="Mean confidence the parser reported across the document, in [0, 1]. NULL when the parser reported none. The grade Docling derives from this is not stored: its thresholds are Docling's, and a stored grade would disagree with a recomputed one after an upgrade.",
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "parse_confidence_low",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Confidence of the worst page, which is the one worth reviewing.",
        existing_comment="Confidence of the worst page. A document can average well and still have one unreadable page, which is the case worth reviewing, so this is the more useful of the two for finding problems.",
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "parse_status",
        existing_type=sa.TEXT(),
        comment="new | pending | in_progress | parsed | failed.",
        existing_comment="new | pending | in_progress | parsed | failed. The queue the parsing service selects on; in_progress is how a worker claims a document so a second worker skips it. A worker that dies leaves the row claimed, and the next run fails it with a reason and retry returns it to pending.",
        existing_nullable=False,
        existing_server_default=sa.text("'new'::text"),
    )
    op.alter_column(
        "documents",
        "parse_claimed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When a worker claimed this document for parsing, NULL when none holds it. What tells a live claim from one a dead worker left behind.",
        existing_comment="When a worker claimed this document for parsing, and NULL whenever it is not claimed. It is what tells a live claim from one a dead worker left behind: without it a second worker starting up cannot sweep abandoned rows without also killing the first worker's work in progress.",
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "chunk_status",
        existing_type=sa.TEXT(),
        comment="new | pending | in_progress | chunked | failed. The only column chunking reads to find work: it does not consult parse_status, because a stage knows of no other stage.",
        existing_comment="new | pending | in_progress | chunked | failed. The queue the chunking service selects on, and the only column it reads to find work: it does not consult parse_status, because a stage knows of no other stage. Starting chunking on a document that was never parsed fails that document, which is the orchestrator's mistake to avoid. Mirrors parse_status in every other respect, including how a dead worker's claim becomes a failure the next run can retry. Extraction has no column here: it queues over passages, because a document is a unit of work that divides very unevenly.",
        existing_nullable=False,
        existing_server_default=sa.text("'new'::text"),
    )
    op.alter_column(
        "documents",
        "chunk_claimed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When a worker claimed this document for chunking, NULL when none holds it.",
        existing_comment="When a worker claimed this document for chunking, and NULL whenever it is not claimed. It is what tells a live claim from one a dead worker left behind: without it a second worker starting up cannot sweep abandoned rows without also killing the first worker's work in progress.",
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "oversized",
        existing_type=sa.INTEGER(),
        comment="Passages the last chunking run stored above EMBEDDING_MAX_TOKENS. Expected to be 0: the chunker splits on that budget, so anything above it means the split did not happen. A tripwire; chunking discards nothing.",
        existing_comment="Passages the last chunking run stored above EMBEDDING_MAX_TOKENS. Expected to be 0: the chunker splits on that same budget, so anything above it means the split did not happen, and the passage will be truncated when it is embedded. A tripwire, not a size policy - chunking discards nothing. It replaced a pair of character counts that recorded what a character ceiling had thrown away, which is how whole tables came to reach no passage and no fact while the document still read as cleanly chunked.",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_documents_chunk_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_parse_status"), table_name="documents")
    op.create_index(
        "ix_documents_chunk_queue",
        "documents",
        ["sha256"],
        unique=False,
        postgresql_where=sa.text("chunk_status IN ('pending', 'in_progress')"),
    )
    op.create_index(
        "ix_documents_parse_queue",
        "documents",
        ["sha256"],
        unique=False,
        postgresql_where=sa.text("parse_status IN ('pending', 'in_progress')"),
    )
    op.create_table_comment(
        "documents",
        "One stored source document. Everything about the act of uploading it lives in ingest_events.",
        existing_comment="One stored source document. Everything about the act of uploading it - filename, size, timestamp - lives in ingest_events. Ingestion writes sha256, mime_type, page_count and char_count; parsing writes the rest.",
        schema=None,
    )
    op.add_column(
        "facts",
        sa.Column(
            "evidence_sentence_ids",
            postgresql.ARRAY(sa.Integer()),
            nullable=False,
            comment="Which of passages.sentences the claim was drawn from. What the extractor chooses; the span below is resolved from it, so a citation is exact by construction rather than by searching for a quote.",
        ),
    )
    op.add_column(
        "facts",
        sa.Column(
            "spacy_model",
            sa.Text(),
            nullable=True,
            comment="The spaCy pipeline that judged this fact.",
        ),
    )
    op.add_column(
        "facts",
        sa.Column(
            "spacy_version",
            sa.Text(),
            nullable=True,
            comment="spaCy version. The parser decides the verdict, so it is provenance in the same way the prompt version is.",
        ),
    )
    op.add_column(
        "facts",
        sa.Column(
            "statement_predicates",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Finite verbs in the statement. One is atomic; more means several claims in one sentence, none means no claim at all.",
        ),
    )
    op.add_column(
        "facts",
        sa.Column(
            "evidence_predicates",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Finite verbs in the cited sentences. Against statement_predicates, how far the passage was decomposed.",
        ),
    )
    op.add_column(
        "facts",
        sa.Column(
            "units_statement",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            comment="The numbers, proper nouns and predicates the statement asserts, which are the parts of it a paraphrase cannot change.",
        ),
    )
    op.add_column(
        "facts",
        sa.Column(
            "units_added",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            comment="Units of the statement that occur nowhere in the cited sentences, in any form. Empty on every accepted fact, which is what says nothing was invented.",
        ),
    )
    op.add_column(
        "facts",
        sa.Column(
            "unresolved_references",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            comment="Pronouns leaving the statement dependent on its context. Empty on every accepted fact, which is what makes a question from it answerable alone.",
        ),
    )
    op.add_column(
        "facts",
        sa.Column(
            "rejection_code",
            sa.Text(),
            nullable=True,
            comment="Which check failed, NULL when none did.",
        ),
    )
    op.alter_column(
        "facts",
        "passage_id",
        existing_type=sa.BIGINT(),
        comment="The passage this fact was drawn from, and the route to both its document and its topics.",
        existing_comment="The passage this fact was extracted from, and the route to both its document and its topic. A fact has no topic column of its own: one value in one place cannot disagree with itself.",
        existing_nullable=False,
    )
    op.alter_column(
        "facts",
        "evidence_text",
        existing_type=sa.TEXT(),
        comment="The cited sentences of the passage, resolved from evidence_sentence_ids.",
        existing_comment="The exact source wording supporting the statement. The evidence_exact gate matches this against the passage text character for character.",
        existing_nullable=False,
    )
    op.alter_column(
        "facts",
        "evidence_start",
        existing_type=sa.INTEGER(),
        comment="Offset of the evidence's first character within passages.text.",
        existing_comment="Offset of the evidence's first character, RELATIVE TO passages.text - not to the page and not to the document.",
        existing_nullable=False,
    )
    op.alter_column(
        "facts",
        "evidence_end",
        existing_type=sa.INTEGER(),
        comment="Offset one past the evidence's last character.",
        existing_comment="Offset one past the evidence's last character, relative to passages.text, so the span is text[evidence_start:evidence_end] and its length is the difference. Present so that evidence appearing twice in one passage is still unambiguous.",
        existing_nullable=False,
    )
    op.alter_column(
        "facts",
        "extraction_method",
        existing_type=sa.TEXT(),
        comment="llm | deterministic.",
        existing_comment="llm | deterministic. Deterministic facts are read straight from table cells and carry no model-error risk; llm facts do. Enforced by a CHECK constraint.",
        existing_nullable=False,
    )
    op.alter_column(
        "facts",
        "extraction_model",
        existing_type=sa.TEXT(),
        comment="The model that wrote the statement, NULL if none did.",
        existing_comment="The model that produced this fact, as the LiteLLM identifier it was called by, and NULL for a deterministic one. Without it the table silently mixes generations: change EXTRACTION_MODEL and there is no way to tell which facts came from which model, which for a deliverable that is itself a reference dataset makes the whole table unciteable.",
        existing_nullable=True,
    )
    op.alter_column(
        "facts",
        "prompt_version",
        existing_type=sa.TEXT(),
        comment="Version of the extraction prompt. The prompt decides what counts as a fact, so two prompts are two datasets.",
        existing_comment="Version of the extraction prompt, NULL for a deterministic fact. The prompt decides what counts as a fact, so two prompts are two datasets; this is what lets them be told apart.",
        existing_nullable=True,
    )
    op.alter_column(
        "facts",
        "extraction_temperature",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Sampling temperature used.",
        existing_comment="Sampling temperature used, NULL for a deterministic fact. Recorded because a fact drawn at temperature 0 is reproducible and one drawn above it is not.",
        existing_nullable=True,
    )
    op.alter_column(
        "facts",
        "validated",
        existing_type=sa.BOOLEAN(),
        comment="Whether every check passed.",
        existing_comment="Whether the evidence was found in the passage.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "facts",
        "validation_error",
        existing_type=sa.TEXT(),
        comment="That failure in words.",
        existing_comment="Why validation failed.",
        existing_nullable=True,
    )
    op.create_index(
        "ix_facts_rejection_code", "facts", ["rejection_code"], unique=False
    )
    op.create_table_comment(
        "facts",
        "One atomic statement drawn from one passage, with the source span supporting it. The unit a question is generated from and scored against.",
        existing_comment="One atomic statement isolated from one passage, with the exact source span supporting it. The unit a question is generated from and scored against. Deliberately industry-agnostic: there are no typed domain entities here, so nothing in this table assumes banking.",
        schema=None,
    )
    op.drop_column("facts", "evidence_occurrences")
    op.alter_column(
        "passage_topics",
        "passage_id",
        existing_type=sa.BIGINT(),
        comment="The passage. Re-chunking deletes it and these rows with it, which is what leaves a fit stale.",
        existing_comment="The passage.",
        existing_nullable=False,
    )
    op.alter_column(
        "passage_topics",
        "topic_id",
        existing_type=sa.BIGINT(),
        comment="The topic.",
        existing_comment="The topic. Deleting a topic removes these membership rows and leaves every passage in place, holding one fewer topic.",
        existing_nullable=False,
    )
    op.alter_column(
        "passage_topics",
        "weight",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Share of this passage attributed to this topic, in (0, 1]. The weights for one passage sum to at most 1, which spans rows and so is not enforced; the only writer is the topic model.",
        existing_comment="Share of this passage attributed to this topic by the model, in (0, 1], enforced by a CHECK constraint. The weights for one passage SHOULD sum to at most 1, but that is NOT enforced: it spans rows, so no row-level constraint can see it and only a trigger could. The writer is trusted, because the only writer is the topic model, which produces a normalised distribution by construction.",
        existing_nullable=False,
    )
    op.create_index(
        "ix_passage_topics_weight",
        "passage_topics",
        ["passage_id", "weight"],
        unique=False,
    )
    op.create_table_comment(
        "passage_topics",
        "The LDA distribution, one row per passage-topic pair above the weight floor. The only place the relationship is stored; the dominant topic is the highest weight, derived rather than stored.",
        existing_comment="How strongly one passage belongs to one topic - the LDA distribution, one row per pair. The only place the passage-to-topic relationship is stored; facts and questions reach their topics by joining through their passage. The dominant topic is the highest weight for a passage, derived rather than stored.",
        schema=None,
    )
    op.add_column(
        "passages",
        sa.Column(
            "sentences",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
            comment="The sentences spaCy found, [{i, start, end, predicates}], with offsets into text. Extraction cites one by index, so a citation needs no quote to search for. NULL until chunking has run under a version that writes it.",
        ),
    )
    op.add_column(
        "passages",
        sa.Column(
            "lemmas",
            postgresql.ARRAY(sa.Text()),
            nullable=True,
            comment="Content lemmas, the vocabulary topic modelling is fitted over. Written here so one segmentation serves both stages and a fit reads a column instead of re-tokenising the corpus.",
        ),
    )
    op.alter_column(
        "passages",
        "ordinal",
        existing_type=sa.INTEGER(),
        comment="Position in reading order within the document, from 1 and contiguous, so ordinal +/- 1 are the neighbouring passages. Reassigned on every re-chunk.",
        existing_comment="Position in reading order within the document, starting at 1 and contiguous. Assigned by the chunker following the order of Docling's structured model, not raw PDF byte order. Contiguity is what makes ordinal +/- 1 the neighbouring passages, which the edge-case generator needs. Reassigned on every re-chunk, so it is not stable across chunking configuration changes.",
        existing_nullable=False,
    )
    op.alter_column(
        "passages",
        "extract_status",
        existing_type=sa.TEXT(),
        comment="new | pending | in_progress | extracted | failed. Extraction queues over passages rather than documents, which is the unit that divides evenly between workers.",
        existing_comment="new | pending | in_progress | extracted | failed. The extraction queue runs over passages rather than documents: one document holds four hundred passages and another thirty, so claiming a document hands one worker hours of work and its neighbour minutes. A passage is one model call, which makes it the unit that divides evenly.",
        existing_nullable=False,
        existing_server_default=sa.text("'new'::text"),
    )
    op.alter_column(
        "passages",
        "page_to",
        existing_type=sa.INTEGER(),
        comment="Page the passage ends on.",
        existing_comment="Page the passage ends on. Differs from page_from when the passage crosses a page break.",
        existing_nullable=True,
    )
    op.alter_column(
        "passages",
        "section_path",
        existing_type=sa.TEXT(),
        comment='Heading trail, for example "3 > 3.2 > Delivery".',
        existing_comment='Heading trail, for example "3 > 3.2 > Delivery". What a reviewer reads to orient themselves.',
        existing_nullable=True,
    )
    op.alter_column(
        "passages",
        "block_type",
        existing_type=sa.TEXT(),
        comment="Docling's DocItemLabel for the source item. Routes extraction: a table goes to the cell reader, everything else to the model. A passage holding items of several kinds is labelled table if any of them is one.",
        existing_comment="Docling's DocItemLabel for the source item: text, section_header, list_item, table, caption, formula and others. Routes extraction: a table passage goes to the deterministic cell reader, everything else to the LLM. A passage holding items of several kinds is labelled table if any of them is one, because reading a table with the model is the more expensive mistake.",
        existing_nullable=True,
    )
    op.alter_column(
        "passages",
        "doc_item_refs",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        comment="The converter's identifiers for the items this passage was cut from, and the only non-fuzzy way back to the converted document.",
        existing_comment="The converter's own identifiers for the items this passage was cut from, for example {#/texts/28,#/texts/31}. The only way back from a stored passage to the converted document in the parsed bucket: without them the mapping is fuzzy text matching, which fails on exactly the repeated boilerplate where it matters. Also the record of what a merged passage is made of, which block_type alone cannot express.",
        existing_nullable=False,
    )
    op.alter_column(
        "passages",
        "bbox",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Where the passage sits, one box per page it spans: [{page, l, t, r, b}], on a top-left origin. NULL when the converter recorded no position.",
        existing_comment="Where the passage sits on the page, one box per page it spans: [{page, l, t, r, b}]. Normalised to a top-left origin, because the converter reports text from the bottom left and table cells from the top left, and a consumer cannot be expected to know which. Stored so that drawing a highlight over the source does not mean fetching and parsing a multi-megabyte document from the object store. NULL when the converter recorded no position.",
        existing_nullable=True,
    )
    op.alter_column(
        "passages",
        "table_cells",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="The cell grids behind a table passage: [{caption, num_rows, num_cols, cells:[{row, col, row_span, col_span, column_header, row_header, text, line}]}]. `line` is the rendered Markdown row the cell sits in and the evidence a fact drawn from it cites; NULL on a header cell. Only the rows this passage renders are kept. NULL unless block_type is table.",
        existing_comment="The cell grid behind a table passage. A list of grids, since one passage can hold more than one table, each {caption, num_rows, num_cols, cells:[{row, col, row_span, col_span, column_header, row_header, text, line}]}. NULL unless block_type is table. `line` is the rendered Markdown row of passages.text the cell sits in, and the evidence any fact drawn from that cell quotes; it is NULL on a header cell, which yields no fact. Only the rows this passage renders are stored: a split table points every piece at the whole item, and a row this piece does not show would describe a value with a row the reader cannot see.",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_passages_extract_status"), table_name="passages")
    op.create_index(
        "ix_passages_extract_queue",
        "passages",
        ["id"],
        unique=False,
        postgresql_where=sa.text("extract_status IN ('pending', 'in_progress')"),
    )
    op.create_table_comment(
        "passages",
        "A document split into retrievable chunks. Immutable: re-chunking deletes and re-inserts every passage of a document.",
        existing_comment="A document split into retrievable chunks. Immutable: re-chunking deletes and re-inserts every passage of a document, which cascades to its facts and questions.",
        schema=None,
    )
    op.alter_column(
        "topics",
        "topic_index",
        existing_type=sa.INTEGER(),
        comment="Position of this topic in the fitted model, and the key scoring a passage returns. NULL means this row is a fit request rather than a topic; NULLs do not collide under a unique constraint.",
        existing_comment="Position of this topic in the fitted model, and the mapping key back to it: scoring a passage returns an index, and this turns that index into a row. Unique, because two rows sharing an index would make that mapping ambiguous. NULL means this row is an outstanding fit request rather than a topic; NULLs do not collide under a unique constraint.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "top_terms",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        comment="Highest-weighted terms, descending. The topic's readable identity and the only signature a label is matched on across a refit.",
        existing_comment="Highest-weighted terms, in descending order. The human-readable identity of the topic, and the only stored signature available for matching a topic across refits. Empty only on a row that is a fit request rather than a topic.",
        existing_nullable=False,
    )
    op.alter_column(
        "topics",
        "label",
        existing_type=sa.TEXT(),
        comment="Name assigned by a person, if any.",
        existing_comment="Name assigned by a person, if any, so reports read a subject rather than a list of terms. Carried across a refit by matching top terms, which is the only signature there is; a topic whose terms have moved too far loses it.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "include_in_coverage",
        existing_type=sa.BOOLEAN(),
        comment="Whether this topic counts toward coverage reporting. Carried across a refit with the label.",
        existing_comment="Whether this topic counts toward coverage reporting. Set false for topics judged too unstable or too diffuse to be a meaningful coverage partition. Carried across a refit with the label.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "topics",
        "status",
        existing_type=sa.TEXT(),
        comment="pending | in_progress | modelled | failed. A finished topic is modelled; the other three describe a fit.",
        existing_comment="pending | in_progress | modelled | failed. A finished topic is modelled; the other three describe a fit rather than a topic. in_progress is how a worker claims a request so a second worker skips it, and a worker that dies leaves the row claimed until the lease expires and the next run fails it with a reason.",
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::text"),
    )
    op.alter_column(
        "topics",
        "error",
        existing_type=sa.TEXT(),
        comment="Why a fit failed, on the request row, which is kept beside the topics the previous fit produced.",
        existing_comment="Why a fit failed. On a failed request row, which is kept beside the topics the previous fit produced - a refit that fails does not take the working model with it.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "claimed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When a worker claimed this fit, NULL when none holds it.",
        existing_comment="When a worker claimed this fit, and NULL whenever it is not claimed. It is what tells a live claim from one a dead worker left behind.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "fitted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the fit completed.",
        existing_comment="When the fit completed, and NULL until it does. The answer to whether the stored topics still describe the corpus as it is now: compare it against the newest document.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "corpus_passages",
        existing_type=sa.INTEGER(),
        comment="How many passages the model was fitted over. Compared against the live count to tell whether the topics still describe the corpus.",
        existing_comment="How many passages the model was fitted over. Repeated on every topic of one fit, because it qualifies each of them: twelve topics over thirty passages are noise, and the number is what says so.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "corpus_vocabulary",
        existing_type=sa.INTEGER(),
        comment="How many terms survived the frequency filter.",
        existing_comment="How many terms survived the frequency filter and so define the topics. A collapse here is the first sign that TOPIC_NO_BELOW or TOPIC_NO_ABOVE is wrong for the corpus.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "passages_without_topics",
        existing_type=sa.INTEGER(),
        comment="How many passages the fit could place in no topic. Those, and the facts drawn from them, are absent from every topic-weighted report.",
        existing_comment="How many passages the fit could place in no topic at all, because every one of their terms was filtered out of the vocabulary. A coverage gap: those passages, and the facts and questions drawn from them, are absent from any topic-weighted report. Counted rather than logged, for the same reason a rejected fact is stored rather than dropped.",
        existing_nullable=True,
    )
    op.create_table_comment(
        "topics",
        "Clusters over the corpus's own vocabulary, fitted by LDA. passage_topics carries the membership; facts and questions reach their topics by joining through their passage. Also the queue: a row with a NULL topic_index is a request to refit.",
        existing_comment="Clusters over the corpus vocabulary, fitted by LDA. Not an LLM and not pretrained: topics are defined over this corpus's own vocabulary, which is what keeps the system industry-agnostic. Standalone by design - it references nothing. passage_topics carries the weighted membership, and facts and questions reach their topics by joining through their passage, so no two rows can disagree about it. Deleting a topic removes its membership rows only. This is also the queue: a row with a NULL topic_index is an outstanding request to refit, not a topic, and a completed fit replaces every row - LDA cannot refit one topic in isolation, so there is no per-topic rediscovery.",
        schema=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Takes it back out.

    The facts deleted on the way up do not come back: the columns holding
    them are dropped below.
    """
    op.execute("DELETE FROM facts")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "topics",
        "Clusters over the corpus vocabulary, fitted by LDA. Not an LLM and not pretrained: topics are defined over this corpus's own vocabulary, which is what keeps the system industry-agnostic. Standalone by design - it references nothing. passage_topics carries the weighted membership, and facts and questions reach their topics by joining through their passage, so no two rows can disagree about it. Deleting a topic removes its membership rows only. This is also the queue: a row with a NULL topic_index is an outstanding request to refit, not a topic, and a completed fit replaces every row - LDA cannot refit one topic in isolation, so there is no per-topic rediscovery.",
        existing_comment="Clusters over the corpus's own vocabulary, fitted by LDA. passage_topics carries the membership; facts and questions reach their topics by joining through their passage. Also the queue: a row with a NULL topic_index is a request to refit.",
        schema=None,
    )
    op.alter_column(
        "topics",
        "passages_without_topics",
        existing_type=sa.INTEGER(),
        comment="How many passages the fit could place in no topic at all, because every one of their terms was filtered out of the vocabulary. A coverage gap: those passages, and the facts and questions drawn from them, are absent from any topic-weighted report. Counted rather than logged, for the same reason a rejected fact is stored rather than dropped.",
        existing_comment="How many passages the fit could place in no topic. Those, and the facts drawn from them, are absent from every topic-weighted report.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "corpus_vocabulary",
        existing_type=sa.INTEGER(),
        comment="How many terms survived the frequency filter and so define the topics. A collapse here is the first sign that TOPIC_NO_BELOW or TOPIC_NO_ABOVE is wrong for the corpus.",
        existing_comment="How many terms survived the frequency filter.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "corpus_passages",
        existing_type=sa.INTEGER(),
        comment="How many passages the model was fitted over. Repeated on every topic of one fit, because it qualifies each of them: twelve topics over thirty passages are noise, and the number is what says so.",
        existing_comment="How many passages the model was fitted over. Compared against the live count to tell whether the topics still describe the corpus.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "fitted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the fit completed, and NULL until it does. The answer to whether the stored topics still describe the corpus as it is now: compare it against the newest document.",
        existing_comment="When the fit completed.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "claimed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When a worker claimed this fit, and NULL whenever it is not claimed. It is what tells a live claim from one a dead worker left behind.",
        existing_comment="When a worker claimed this fit, NULL when none holds it.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "error",
        existing_type=sa.TEXT(),
        comment="Why a fit failed. On a failed request row, which is kept beside the topics the previous fit produced - a refit that fails does not take the working model with it.",
        existing_comment="Why a fit failed, on the request row, which is kept beside the topics the previous fit produced.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "status",
        existing_type=sa.TEXT(),
        comment="pending | in_progress | modelled | failed. A finished topic is modelled; the other three describe a fit rather than a topic. in_progress is how a worker claims a request so a second worker skips it, and a worker that dies leaves the row claimed until the lease expires and the next run fails it with a reason.",
        existing_comment="pending | in_progress | modelled | failed. A finished topic is modelled; the other three describe a fit.",
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::text"),
    )
    op.alter_column(
        "topics",
        "include_in_coverage",
        existing_type=sa.BOOLEAN(),
        comment="Whether this topic counts toward coverage reporting. Set false for topics judged too unstable or too diffuse to be a meaningful coverage partition. Carried across a refit with the label.",
        existing_comment="Whether this topic counts toward coverage reporting. Carried across a refit with the label.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "topics",
        "label",
        existing_type=sa.TEXT(),
        comment="Name assigned by a person, if any, so reports read a subject rather than a list of terms. Carried across a refit by matching top terms, which is the only signature there is; a topic whose terms have moved too far loses it.",
        existing_comment="Name assigned by a person, if any.",
        existing_nullable=True,
    )
    op.alter_column(
        "topics",
        "top_terms",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        comment="Highest-weighted terms, in descending order. The human-readable identity of the topic, and the only stored signature available for matching a topic across refits. Empty only on a row that is a fit request rather than a topic.",
        existing_comment="Highest-weighted terms, descending. The topic's readable identity and the only signature a label is matched on across a refit.",
        existing_nullable=False,
    )
    op.alter_column(
        "topics",
        "topic_index",
        existing_type=sa.INTEGER(),
        comment="Position of this topic in the fitted model, and the mapping key back to it: scoring a passage returns an index, and this turns that index into a row. Unique, because two rows sharing an index would make that mapping ambiguous. NULL means this row is an outstanding fit request rather than a topic; NULLs do not collide under a unique constraint.",
        existing_comment="Position of this topic in the fitted model, and the key scoring a passage returns. NULL means this row is a fit request rather than a topic; NULLs do not collide under a unique constraint.",
        existing_nullable=True,
    )
    op.create_table_comment(
        "passages",
        "A document split into retrievable chunks. Immutable: re-chunking deletes and re-inserts every passage of a document, which cascades to its facts and questions.",
        existing_comment="A document split into retrievable chunks. Immutable: re-chunking deletes and re-inserts every passage of a document.",
        schema=None,
    )
    op.drop_index(
        "ix_passages_extract_queue",
        table_name="passages",
        postgresql_where=sa.text("extract_status IN ('pending', 'in_progress')"),
    )
    op.create_index(
        op.f("ix_passages_extract_status"), "passages", ["extract_status"], unique=False
    )
    op.alter_column(
        "passages",
        "table_cells",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="The cell grid behind a table passage. A list of grids, since one passage can hold more than one table, each {caption, num_rows, num_cols, cells:[{row, col, row_span, col_span, column_header, row_header, text, line}]}. NULL unless block_type is table. `line` is the rendered Markdown row of passages.text the cell sits in, and the evidence any fact drawn from that cell quotes; it is NULL on a header cell, which yields no fact. Only the rows this passage renders are stored: a split table points every piece at the whole item, and a row this piece does not show would describe a value with a row the reader cannot see.",
        existing_comment="The cell grids behind a table passage: [{caption, num_rows, num_cols, cells:[{row, col, row_span, col_span, column_header, row_header, text, line}]}]. `line` is the rendered Markdown row the cell sits in and the evidence a fact drawn from it cites; NULL on a header cell. Only the rows this passage renders are kept. NULL unless block_type is table.",
        existing_nullable=True,
    )
    op.alter_column(
        "passages",
        "bbox",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Where the passage sits on the page, one box per page it spans: [{page, l, t, r, b}]. Normalised to a top-left origin, because the converter reports text from the bottom left and table cells from the top left, and a consumer cannot be expected to know which. Stored so that drawing a highlight over the source does not mean fetching and parsing a multi-megabyte document from the object store. NULL when the converter recorded no position.",
        existing_comment="Where the passage sits, one box per page it spans: [{page, l, t, r, b}], on a top-left origin. NULL when the converter recorded no position.",
        existing_nullable=True,
    )
    op.alter_column(
        "passages",
        "doc_item_refs",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        comment="The converter's own identifiers for the items this passage was cut from, for example {#/texts/28,#/texts/31}. The only way back from a stored passage to the converted document in the parsed bucket: without them the mapping is fuzzy text matching, which fails on exactly the repeated boilerplate where it matters. Also the record of what a merged passage is made of, which block_type alone cannot express.",
        existing_comment="The converter's identifiers for the items this passage was cut from, and the only non-fuzzy way back to the converted document.",
        existing_nullable=False,
    )
    op.alter_column(
        "passages",
        "block_type",
        existing_type=sa.TEXT(),
        comment="Docling's DocItemLabel for the source item: text, section_header, list_item, table, caption, formula and others. Routes extraction: a table passage goes to the deterministic cell reader, everything else to the LLM. A passage holding items of several kinds is labelled table if any of them is one, because reading a table with the model is the more expensive mistake.",
        existing_comment="Docling's DocItemLabel for the source item. Routes extraction: a table goes to the cell reader, everything else to the model. A passage holding items of several kinds is labelled table if any of them is one.",
        existing_nullable=True,
    )
    op.alter_column(
        "passages",
        "section_path",
        existing_type=sa.TEXT(),
        comment='Heading trail, for example "3 > 3.2 > Delivery". What a reviewer reads to orient themselves.',
        existing_comment='Heading trail, for example "3 > 3.2 > Delivery".',
        existing_nullable=True,
    )
    op.alter_column(
        "passages",
        "page_to",
        existing_type=sa.INTEGER(),
        comment="Page the passage ends on. Differs from page_from when the passage crosses a page break.",
        existing_comment="Page the passage ends on.",
        existing_nullable=True,
    )
    op.alter_column(
        "passages",
        "extract_status",
        existing_type=sa.TEXT(),
        comment="new | pending | in_progress | extracted | failed. The extraction queue runs over passages rather than documents: one document holds four hundred passages and another thirty, so claiming a document hands one worker hours of work and its neighbour minutes. A passage is one model call, which makes it the unit that divides evenly.",
        existing_comment="new | pending | in_progress | extracted | failed. Extraction queues over passages rather than documents, which is the unit that divides evenly between workers.",
        existing_nullable=False,
        existing_server_default=sa.text("'new'::text"),
    )
    op.alter_column(
        "passages",
        "ordinal",
        existing_type=sa.INTEGER(),
        comment="Position in reading order within the document, starting at 1 and contiguous. Assigned by the chunker following the order of Docling's structured model, not raw PDF byte order. Contiguity is what makes ordinal +/- 1 the neighbouring passages, which the edge-case generator needs. Reassigned on every re-chunk, so it is not stable across chunking configuration changes.",
        existing_comment="Position in reading order within the document, from 1 and contiguous, so ordinal +/- 1 are the neighbouring passages. Reassigned on every re-chunk.",
        existing_nullable=False,
    )
    op.drop_column("passages", "lemmas")
    op.drop_column("passages", "sentences")
    op.create_table_comment(
        "passage_topics",
        "How strongly one passage belongs to one topic - the LDA distribution, one row per pair. The only place the passage-to-topic relationship is stored; facts and questions reach their topics by joining through their passage. The dominant topic is the highest weight for a passage, derived rather than stored.",
        existing_comment="The LDA distribution, one row per passage-topic pair above the weight floor. The only place the relationship is stored; the dominant topic is the highest weight, derived rather than stored.",
        schema=None,
    )
    op.drop_index("ix_passage_topics_weight", table_name="passage_topics")
    op.alter_column(
        "passage_topics",
        "weight",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Share of this passage attributed to this topic by the model, in (0, 1], enforced by a CHECK constraint. The weights for one passage SHOULD sum to at most 1, but that is NOT enforced: it spans rows, so no row-level constraint can see it and only a trigger could. The writer is trusted, because the only writer is the topic model, which produces a normalised distribution by construction.",
        existing_comment="Share of this passage attributed to this topic, in (0, 1]. The weights for one passage sum to at most 1, which spans rows and so is not enforced; the only writer is the topic model.",
        existing_nullable=False,
    )
    op.alter_column(
        "passage_topics",
        "topic_id",
        existing_type=sa.BIGINT(),
        comment="The topic. Deleting a topic removes these membership rows and leaves every passage in place, holding one fewer topic.",
        existing_comment="The topic.",
        existing_nullable=False,
    )
    op.alter_column(
        "passage_topics",
        "passage_id",
        existing_type=sa.BIGINT(),
        comment="The passage.",
        existing_comment="The passage. Re-chunking deletes it and these rows with it, which is what leaves a fit stale.",
        existing_nullable=False,
    )
    op.add_column(
        "facts",
        sa.Column(
            "evidence_occurrences",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
            comment="How many times the evidence appears in the passage. One means the stored span is the only candidate and the citation is exact. More means the span is the FIRST of several identical ones and may not be the copy the fact was drawn from - nothing in a model's answer says which, so the ambiguity is recorded rather than guessed at. Filter on this when a citation has to be unambiguous.",
        ),
    )
    op.create_table_comment(
        "facts",
        "One atomic statement isolated from one passage, with the exact source span supporting it. The unit a question is generated from and scored against. Deliberately industry-agnostic: there are no typed domain entities here, so nothing in this table assumes banking.",
        existing_comment="One atomic statement drawn from one passage, with the source span supporting it. The unit a question is generated from and scored against.",
        schema=None,
    )
    op.drop_index("ix_facts_rejection_code", table_name="facts")
    op.alter_column(
        "facts",
        "validation_error",
        existing_type=sa.TEXT(),
        comment="Why validation failed.",
        existing_comment="That failure in words.",
        existing_nullable=True,
    )
    op.alter_column(
        "facts",
        "validated",
        existing_type=sa.BOOLEAN(),
        comment="Whether the evidence was found in the passage.",
        existing_comment="Whether every check passed.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "facts",
        "extraction_temperature",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Sampling temperature used, NULL for a deterministic fact. Recorded because a fact drawn at temperature 0 is reproducible and one drawn above it is not.",
        existing_comment="Sampling temperature used.",
        existing_nullable=True,
    )
    op.alter_column(
        "facts",
        "prompt_version",
        existing_type=sa.TEXT(),
        comment="Version of the extraction prompt, NULL for a deterministic fact. The prompt decides what counts as a fact, so two prompts are two datasets; this is what lets them be told apart.",
        existing_comment="Version of the extraction prompt. The prompt decides what counts as a fact, so two prompts are two datasets.",
        existing_nullable=True,
    )
    op.alter_column(
        "facts",
        "extraction_model",
        existing_type=sa.TEXT(),
        comment="The model that produced this fact, as the LiteLLM identifier it was called by, and NULL for a deterministic one. Without it the table silently mixes generations: change EXTRACTION_MODEL and there is no way to tell which facts came from which model, which for a deliverable that is itself a reference dataset makes the whole table unciteable.",
        existing_comment="The model that wrote the statement, NULL if none did.",
        existing_nullable=True,
    )
    op.alter_column(
        "facts",
        "extraction_method",
        existing_type=sa.TEXT(),
        comment="llm | deterministic. Deterministic facts are read straight from table cells and carry no model-error risk; llm facts do. Enforced by a CHECK constraint.",
        existing_comment="llm | deterministic.",
        existing_nullable=False,
    )
    op.alter_column(
        "facts",
        "evidence_end",
        existing_type=sa.INTEGER(),
        comment="Offset one past the evidence's last character, relative to passages.text, so the span is text[evidence_start:evidence_end] and its length is the difference. Present so that evidence appearing twice in one passage is still unambiguous.",
        existing_comment="Offset one past the evidence's last character.",
        existing_nullable=False,
    )
    op.alter_column(
        "facts",
        "evidence_start",
        existing_type=sa.INTEGER(),
        comment="Offset of the evidence's first character, RELATIVE TO passages.text - not to the page and not to the document.",
        existing_comment="Offset of the evidence's first character within passages.text.",
        existing_nullable=False,
    )
    op.alter_column(
        "facts",
        "evidence_text",
        existing_type=sa.TEXT(),
        comment="The exact source wording supporting the statement. The evidence_exact gate matches this against the passage text character for character.",
        existing_comment="The cited sentences of the passage, resolved from evidence_sentence_ids.",
        existing_nullable=False,
    )
    op.alter_column(
        "facts",
        "passage_id",
        existing_type=sa.BIGINT(),
        comment="The passage this fact was extracted from, and the route to both its document and its topic. A fact has no topic column of its own: one value in one place cannot disagree with itself.",
        existing_comment="The passage this fact was drawn from, and the route to both its document and its topics.",
        existing_nullable=False,
    )
    op.drop_column("facts", "rejection_code")
    op.drop_column("facts", "unresolved_references")
    op.drop_column("facts", "units_added")
    op.drop_column("facts", "units_statement")
    op.drop_column("facts", "evidence_predicates")
    op.drop_column("facts", "statement_predicates")
    op.drop_column("facts", "spacy_version")
    op.drop_column("facts", "spacy_model")
    op.drop_column("facts", "evidence_sentence_ids")
    op.create_table_comment(
        "documents",
        "One stored source document. Everything about the act of uploading it - filename, size, timestamp - lives in ingest_events. Ingestion writes sha256, mime_type, page_count and char_count; parsing writes the rest.",
        existing_comment="One stored source document. Everything about the act of uploading it lives in ingest_events.",
        schema=None,
    )
    op.drop_index(
        "ix_documents_parse_queue",
        table_name="documents",
        postgresql_where=sa.text("parse_status IN ('pending', 'in_progress')"),
    )
    op.drop_index(
        "ix_documents_chunk_queue",
        table_name="documents",
        postgresql_where=sa.text("chunk_status IN ('pending', 'in_progress')"),
    )
    op.create_index(
        op.f("ix_documents_parse_status"), "documents", ["parse_status"], unique=False
    )
    op.create_index(
        op.f("ix_documents_chunk_status"), "documents", ["chunk_status"], unique=False
    )
    op.alter_column(
        "documents",
        "oversized",
        existing_type=sa.INTEGER(),
        comment="Passages the last chunking run stored above EMBEDDING_MAX_TOKENS. Expected to be 0: the chunker splits on that same budget, so anything above it means the split did not happen, and the passage will be truncated when it is embedded. A tripwire, not a size policy - chunking discards nothing. It replaced a pair of character counts that recorded what a character ceiling had thrown away, which is how whole tables came to reach no passage and no fact while the document still read as cleanly chunked.",
        existing_comment="Passages the last chunking run stored above EMBEDDING_MAX_TOKENS. Expected to be 0: the chunker splits on that budget, so anything above it means the split did not happen. A tripwire; chunking discards nothing.",
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "chunk_claimed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When a worker claimed this document for chunking, and NULL whenever it is not claimed. It is what tells a live claim from one a dead worker left behind: without it a second worker starting up cannot sweep abandoned rows without also killing the first worker's work in progress.",
        existing_comment="When a worker claimed this document for chunking, NULL when none holds it.",
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "chunk_status",
        existing_type=sa.TEXT(),
        comment="new | pending | in_progress | chunked | failed. The queue the chunking service selects on, and the only column it reads to find work: it does not consult parse_status, because a stage knows of no other stage. Starting chunking on a document that was never parsed fails that document, which is the orchestrator's mistake to avoid. Mirrors parse_status in every other respect, including how a dead worker's claim becomes a failure the next run can retry. Extraction has no column here: it queues over passages, because a document is a unit of work that divides very unevenly.",
        existing_comment="new | pending | in_progress | chunked | failed. The only column chunking reads to find work: it does not consult parse_status, because a stage knows of no other stage.",
        existing_nullable=False,
        existing_server_default=sa.text("'new'::text"),
    )
    op.alter_column(
        "documents",
        "parse_claimed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When a worker claimed this document for parsing, and NULL whenever it is not claimed. It is what tells a live claim from one a dead worker left behind: without it a second worker starting up cannot sweep abandoned rows without also killing the first worker's work in progress.",
        existing_comment="When a worker claimed this document for parsing, NULL when none holds it. What tells a live claim from one a dead worker left behind.",
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "parse_status",
        existing_type=sa.TEXT(),
        comment="new | pending | in_progress | parsed | failed. The queue the parsing service selects on; in_progress is how a worker claims a document so a second worker skips it. A worker that dies leaves the row claimed, and the next run fails it with a reason and retry returns it to pending.",
        existing_comment="new | pending | in_progress | parsed | failed.",
        existing_nullable=False,
        existing_server_default=sa.text("'new'::text"),
    )
    op.alter_column(
        "documents",
        "parse_confidence_low",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Confidence of the worst page. A document can average well and still have one unreadable page, which is the case worth reviewing, so this is the more useful of the two for finding problems.",
        existing_comment="Confidence of the worst page, which is the one worth reviewing.",
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "parse_confidence",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Mean confidence the parser reported across the document, in [0, 1]. NULL when the parser reported none. The grade Docling derives from this is not stored: its thresholds are Docling's, and a stored grade would disagree with a recomputed one after an upgrade.",
        existing_comment="Mean confidence the parser reported, in [0, 1].",
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "content_sha256",
        existing_type=sa.CHAR(length=64),
        comment='SHA-256 of the body text - table cell values included - with page_header and page_footer blocks removed, so a re-export of the same page hashes identically despite different bytes while two revisions of a table differing only in their numbers do not. Only parsing can produce it, because only Docling classifies blocks by layout. Nothing acts on it at ingest; it answers "do we already have this content?" on request.',
        existing_comment='SHA-256 of the body text with whitespace collapsed and case folded. Answers "do we already have this content?" on request; nothing acts on it at ingest.',
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "language",
        existing_type=sa.CHAR(length=2),
        comment="ISO 639-1, NULL until parsing detects it. Constrained to the shape of a code, not to a list of them: which languages the corpus holds is PARSING_LANGUAGES, and the detector can only answer from that set. Note the OCR configuration uses 639-2 codes instead.",
        existing_comment="ISO 639-1, NULL until parsing detects it. Selects the spaCy pipeline chunking and extraction read this document with.",
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "char_count",
        existing_type=sa.INTEGER(),
        comment="Extractable characters, counted by PyMuPDF at upload. Zero suggests a scanned document.",
        existing_comment="Extractable characters, counted by PyMuPDF at upload.",
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "mime_type",
        existing_type=sa.TEXT(),
        comment="Detected from the leading bytes at upload. The type declared by the upload form is ignored.",
        existing_comment="Detected from the leading bytes at upload.",
        existing_nullable=False,
    )
    op.alter_column(
        "documents",
        "sha256",
        existing_type=sa.CHAR(length=64),
        comment="SHA-256 of the raw file bytes. Primary key, and the object key in both buckets: documents/{sha[0:2]}/{sha[2:4]}/{sha} with the extension mime_type implies, and parsed/.../{sha}.json. The 2x2-hex fanout keeps the SeaweedFS filer off a single hot directory. Both keys are derived in code, never stored.",
        existing_comment="SHA-256 of the raw file bytes, and the object key in both buckets: documents/{sha[0:2]}/{sha[2:4]}/{sha}.{ext} and parsed/.../{sha}.json. Both keys are derived in code, never stored.",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
